import type { StepType } from '@buildpilot/shared-types';

export interface StepFieldSchema {
  name: string;
  label: string;
  // 'branchSelect'  = project-aware combobox populated with the project's
  //                   local + remote branches.
  // 'hostSelect'    = combobox listing entries from ~/.buildpilot/hosts.json
  //                   plus an "(inline)" option that hands control back to
  //                   the host/identityFile/password fields below it.
  // The host UI supplies both lists.
  type: 'text' | 'textarea' | 'select' | 'number' | 'branchSelect' | 'hostSelect';
  options?: readonly string[];
  required?: boolean;
  placeholder?: string;
  help?: string;
  defaultValue?: string | number;
}

export interface StepDefinition {
  type: StepType;
  label: string;
  description: string;
  color: string; // background colour for the React Flow node
  icon: string;  // lucide-react icon name
  fields: readonly StepFieldSchema[];
}

const UNITY_BUILD_TARGETS = [
  'StandaloneLinux64',
  'StandaloneWindows64',
  'StandaloneOSX',
  'iOS',
  'Android',
  'WebGL',
] as const;

// Reusable field bundles for steps that share the same shape. Hoisted here so
// we don't have to copy-paste the 4-or-5 host/credentials fields per step.
const REMOTE_HOST_FIELDS: readonly StepFieldSchema[] = [
  {
    name: 'hostId',
    label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
    type: 'hostSelect',
  },
  {
    name: 'host',
    label: 'Inline host',
    type: 'text',
    placeholder: 'build@mac-builder.local',
  },
  {
    name: 'identityFile',
    label: 'Identity file',
    type: 'text',
    placeholder: '~/.ssh/id_ed25519',
  },
  {
    name: 'password',
    label: 'SSH password',
    type: 'text',
    placeholder: '(use this OR identityFile)',
  },
];

const ASC_CRED_FIELDS: readonly StepFieldSchema[] = [
  {
    name: 'keyId',
    label: 'ASC API Key ID',
    type: 'text',
    required: true,
    placeholder: 'ABCDEFGH12',
  },
  {
    name: 'issuerId',
    label: 'ASC Issuer ID',
    type: 'text',
    required: true,
    placeholder: '57246542-96fe-1a63-e053-0824d011072a',
  },
  {
    name: 'apiKeyPath',
    label: 'AuthKey .p8 path (or paste contents below)',
    type: 'text',
    placeholder: '~/.appstoreconnect/private_keys/AuthKey_ABCDEFGH12.p8',
  },
  {
    name: 'apiKeyContents',
    label: '.p8 contents (paste; encrypted at rest)',
    type: 'textarea',
    placeholder: '-----BEGIN PRIVATE KEY-----\n…\n-----END PRIVATE KEY-----',
  },
];

export const STEP_DEFINITIONS: Record<StepType, StepDefinition> = {
  checkout: {
    type: 'checkout',
    label: 'Checkout',
    description: 'Switch the project working tree to a specific branch.',
    color: '#0ea5e9',
    icon: 'GitBranch',
    fields: [
      { name: 'branch', label: 'Branch', type: 'branchSelect', required: true },
    ],
  },
  pull: {
    type: 'pull',
    label: 'Pull',
    description: 'Fetch and fast-forward the current branch from the remote.',
    color: '#10b981',
    icon: 'ArrowDownToLine',
    fields: [
      { name: 'remote', label: 'Remote', type: 'text', placeholder: 'origin' },
    ],
  },
  gitMerge: {
    type: 'gitMerge',
    label: 'Git Merge',
    description: 'Merge another branch into the current one (compose with AI auto-fix to resolve conflicts).',
    color: '#14b8a6',
    icon: 'GitMerge',
    fields: [
      { name: 'sourceBranch', label: 'Source branch', type: 'branchSelect', required: true },
      {
        name: 'noFastForward',
        label: 'Always create a merge commit (--no-ff)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'message',
        label: 'Commit message (optional)',
        type: 'text',
        placeholder: 'Merge {{source}} into {{current}}',
      },
    ],
  },
  shell: {
    type: 'shell',
    label: 'Shell',
    description: 'Run an arbitrary shell command inside the project directory.',
    color: '#f59e0b',
    icon: 'Terminal',
    fields: [
      {
        name: 'command',
        label: 'Command',
        type: 'textarea',
        required: true,
        placeholder: 'pnpm install && pnpm test',
      },
      {
        name: 'cwd',
        label: 'Working dir (relative)',
        type: 'text',
        placeholder: '. (defaults to project root)',
      },
    ],
  },
  unityBatch: {
    type: 'unityBatch',
    label: 'Unity Batch Build',
    description: 'Run Unity in batch mode and invoke a static build method.',
    color: '#a855f7',
    icon: 'Gamepad2',
    fields: [
      {
        name: 'unityPath',
        label: 'Unity executable path',
        type: 'text',
        required: true,
        placeholder: 'C:/Program Files/Unity/Hub/Editor/<version>/Editor/Unity.exe',
      },
      {
        name: 'buildTarget',
        label: 'Build target',
        type: 'select',
        required: true,
        options: UNITY_BUILD_TARGETS,
      },
      {
        name: 'executeMethod',
        label: 'Static method',
        type: 'text',
        required: true,
        placeholder: 'BuildScript.BuildDedicatedServer',
      },
      {
        name: 'extraArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: '-customArg value',
      },
      {
        name: 'logPath',
        label: 'Log file path',
        type: 'text',
        placeholder: '(optional — otherwise streamed to stdout)',
      },
    ],
  },
  httpRequest: {
    type: 'httpRequest',
    label: 'HTTP Request',
    description: 'Make an HTTP call and fail the step on a non-success status.',
    color: '#06b6d4',
    icon: 'Globe',
    fields: [
      {
        name: 'method',
        label: 'Method',
        type: 'select',
        required: true,
        options: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] as const,
        defaultValue: 'POST',
      },
      {
        name: 'url',
        label: 'URL',
        type: 'text',
        required: true,
        placeholder: 'https://api.example.com/build-finished',
      },
      {
        name: 'headers',
        label: 'Headers (one per line, "Key: Value")',
        type: 'textarea',
        placeholder: 'Authorization: Bearer ${env.TOKEN}\nContent-Type: application/json',
      },
      {
        name: 'body',
        label: 'Body',
        type: 'textarea',
        placeholder: '{"status":"green"}',
      },
      {
        name: 'expectedStatus',
        label: 'Expected status (comma-separated)',
        type: 'text',
        placeholder: '200,201,204 (defaults to 2xx)',
      },
    ],
  },
  slackNotify: {
    type: 'slackNotify',
    label: 'Slack Notify',
    description: 'Post a message to a Slack incoming webhook.',
    color: '#22d3ee',
    icon: 'MessageSquare',
    fields: [
      {
        name: 'webhookUrl',
        label: 'Webhook URL',
        type: 'text',
        required: true,
        placeholder: 'https://hooks.slack.com/services/T.../B.../...',
      },
      {
        name: 'text',
        label: 'Message',
        type: 'textarea',
        required: true,
        placeholder: ':white_check_mark: Build finished',
      },
    ],
  },
  discordNotify: {
    type: 'discordNotify',
    label: 'Discord Notify',
    description: 'Post a message to a Discord webhook.',
    color: '#8b5cf6',
    icon: 'MessageCircle',
    fields: [
      {
        name: 'webhookUrl',
        label: 'Webhook URL',
        type: 'text',
        required: true,
        placeholder: 'https://discord.com/api/webhooks/.../...',
      },
      {
        name: 'content',
        label: 'Message',
        type: 'textarea',
        required: true,
        placeholder: '✅ Build finished',
      },
    ],
  },
  telegramNotify: {
    type: 'telegramNotify',
    label: 'Telegram Notify',
    description: 'Send a message via Telegram Bot API (token + chat fall back to ~/.buildpilot/config.json).',
    color: '#38bdf8',
    icon: 'Send',
    fields: [
      {
        name: 'botToken',
        label: 'Bot token (leave blank for default)',
        type: 'text',
        placeholder: '123456:ABC-DEF…',
      },
      {
        name: 'chatId',
        label: 'Chat id (leave blank for default)',
        type: 'text',
        placeholder: '@yourchannel or 12345678',
      },
      {
        name: 'text',
        label: 'Message',
        type: 'textarea',
        required: true,
        placeholder: '✅ NetworkTest server build finished\n<i>commit</i> <code>{{sha}}</code>',
      },
      {
        name: 'parseMode',
        label: 'Parse mode',
        type: 'select',
        options: ['plain', 'HTML', 'MarkdownV2'] as const,
        defaultValue: 'plain',
      },
      {
        name: 'silent',
        label: 'Send silently (no sound)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
    ],
  },
  remoteSsh: {
    type: 'remoteSsh',
    label: 'Remote SSH',
    description: 'Run a shell command on a remote host via ssh — the foundation for cross-OS builds.',
    color: '#64748b',
    icon: 'Server',
    fields: [
      {
        name: 'hostId',
        label: 'Saved host (or pick "(inline)" to type one below)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Host (used when no saved host is picked)',
        type: 'text',
        placeholder: 'user@mac-builder.local',
        help: 'Optionally include a port: user@host:2222',
      },
      {
        name: 'identityFile',
        label: 'Identity file (use this OR password)',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'Password (plaintext — see secrets warning)',
        type: 'text',
        placeholder: '(leave blank to use identityFile)',
      },
      {
        name: 'cwd',
        label: 'Remote working dir',
        type: 'text',
        placeholder: '/Users/build/projects/MyGame',
      },
      {
        name: 'command',
        label: 'Command',
        type: 'textarea',
        required: true,
        placeholder: 'git pull && xcodebuild -scheme MyGame -configuration Release archive',
      },
      {
        name: 'skipStrictHostKey',
        label: 'Skip strict host key checking',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
    ],
  },
  sftpUpload: {
    type: 'sftpUpload',
    label: 'SFTP Upload',
    description: 'Upload a single file over SSH/SFTP (key or password auth).',
    color: '#475569',
    icon: 'Upload',
    fields: [
      {
        name: 'hostId',
        label: 'Saved host (or pick "(inline)" to type one below)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Host (used when no saved host is picked)',
        type: 'text',
        placeholder: 'root@game-server.example:22',
      },
      {
        name: 'identityFile',
        label: 'Identity file (use this OR password)',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'Password (plaintext — see secrets warning)',
        type: 'text',
        placeholder: '(leave blank to use identityFile)',
      },
      {
        name: 'localPath',
        label: 'Local file (relative to project, or absolute)',
        type: 'text',
        required: true,
        placeholder: 'Builds/Server.rar',
      },
      {
        name: 'remotePath',
        label: 'Remote destination (absolute path)',
        type: 'text',
        required: true,
        placeholder: '/home/Game/Server.rar',
      },
      {
        name: 'skipStrictHostKey',
        label: 'Skip strict host key checking',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
    ],
  },
  s3Upload: {
    type: 's3Upload',
    label: 'S3 Upload',
    description: 'Upload a file to AWS S3 with optional presigned URL + manifest. Stores credentials in plaintext.',
    color: '#fb923c',
    icon: 'CloudUpload',
    fields: [
      {
        name: 'accessKeyId',
        label: 'AWS Access Key ID (plaintext — secrets vault TBD)',
        type: 'text',
        required: true,
        placeholder: 'AKIA…',
      },
      {
        name: 'secretAccessKey',
        label: 'AWS Secret Access Key',
        type: 'text',
        required: true,
        placeholder: '40-char secret',
      },
      {
        name: 'region',
        label: 'Region',
        type: 'text',
        required: true,
        placeholder: 'eu-central-1',
      },
      {
        name: 'bucket',
        label: 'Bucket',
        type: 'text',
        required: true,
        placeholder: 'my-build-bucket',
      },
      {
        name: 'localPath',
        label: 'Local file',
        type: 'text',
        required: true,
        placeholder: 'Builds/Server.rar',
      },
      {
        name: 'key',
        label: 'S3 object key (path inside bucket)',
        type: 'text',
        required: true,
        placeholder: 'linux-x86_64/Server.rar',
      },
      {
        name: 'storageClass',
        label: 'Storage class',
        type: 'select',
        options: [
          'STANDARD',
          'STANDARD_IA',
          'REDUCED_REDUNDANCY',
          'GLACIER',
          'DEEP_ARCHIVE',
        ] as const,
        defaultValue: 'STANDARD',
      },
      {
        name: 'makePresignedUrl',
        label: 'Generate presigned URL',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'presignedExpiresSec',
        label: 'Presigned URL expiry (seconds)',
        type: 'number',
        placeholder: '604800 = 7 days',
      },
      {
        name: 'manifestKey',
        label: 'Manifest object key (optional, e.g. stable.json)',
        type: 'text',
        placeholder: 'stable.json',
      },
      {
        name: 'manifestChannel',
        label: 'Manifest channel',
        type: 'text',
        placeholder: 'stable',
      },
      {
        name: 'manifestPlatform',
        label: 'Manifest platform',
        type: 'text',
        placeholder: 'linux-x86_64',
      },
    ],
  },
  xcodebuild: {
    type: 'xcodebuild',
    label: 'xcodebuild',
    description: 'Drive xcodebuild for iOS / macOS builds. Local or via a saved Mac host.',
    color: '#0891b2',
    icon: 'Apple',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host (used when no saved host is picked)',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'workspacePath',
        label: 'Workspace (.xcworkspace, optional)',
        type: 'text',
        placeholder: 'MyGame.xcworkspace',
      },
      {
        name: 'projectPath',
        label: 'Project (.xcodeproj, used if no workspace)',
        type: 'text',
        placeholder: 'MyGame.xcodeproj',
      },
      {
        name: 'scheme',
        label: 'Scheme (required for build / archive / test / clean)',
        type: 'text',
        placeholder: 'MyGame',
      },
      {
        name: 'configuration',
        label: 'Configuration',
        type: 'select',
        options: ['Debug', 'Release'] as const,
        defaultValue: 'Release',
      },
      {
        name: 'buildAction',
        label: 'Action',
        type: 'select',
        options: ['build', 'archive', 'test', 'clean', 'exportArchive'] as const,
        defaultValue: 'archive',
      },
      {
        name: 'destination',
        label: 'Destination',
        type: 'text',
        placeholder: 'generic/platform=iOS',
      },
      {
        name: 'archivePath',
        label: 'Archive path (archive: output, exportArchive: input)',
        type: 'text',
        placeholder: 'build/MyGame.xcarchive',
      },
      {
        name: 'exportPath',
        label: 'Export output dir (exportArchive only)',
        type: 'text',
        placeholder: 'build/export',
      },
      {
        name: 'exportOptionsPlist',
        label: 'ExportOptions.plist path (exportArchive only)',
        type: 'text',
        placeholder: 'signing/ExportOptions.plist',
      },
      {
        name: 'additionalArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: 'CODE_SIGNING_ALLOWED=NO',
      },
    ],
  },
  testflightUpload: {
    type: 'testflightUpload',
    label: 'TestFlight Upload',
    description: 'Upload an .ipa to App Store Connect / TestFlight via xcrun altool.',
    color: '#0ea5e9',
    icon: 'PlaneTakeoff',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host (used when no saved host is picked)',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'ipaPath',
        label: '.ipa path',
        type: 'text',
        required: true,
        placeholder: 'build/MyGame.ipa',
      },
      {
        name: 'platform',
        label: 'Platform',
        type: 'select',
        options: ['ios', 'macos', 'tvos'] as const,
        defaultValue: 'ios',
      },
      {
        name: 'authMethod',
        label: 'Auth method',
        type: 'select',
        options: ['apiKey', 'appleId'] as const,
        defaultValue: 'apiKey',
      },
      {
        name: 'apiKeyId',
        label: 'API Key ID (apiKey auth)',
        type: 'text',
        placeholder: 'ABC123XYZ',
        help: 'Place AuthKey_<id>.p8 at ~/.appstoreconnect/private_keys/ on the host.',
      },
      {
        name: 'apiIssuerId',
        label: 'API Issuer ID (apiKey auth)',
        type: 'text',
        placeholder: '57246542-96fe-1a63-e053-0824d011072a',
      },
      {
        name: 'appleId',
        label: 'Apple ID (appleId auth)',
        type: 'text',
        placeholder: 'developer@example.com',
      },
      {
        name: 'appPassword',
        label: 'App-specific password (appleId auth — plaintext)',
        type: 'text',
        placeholder: 'xxxx-xxxx-xxxx-xxxx',
      },
      {
        name: 'additionalArgs',
        label: 'Extra altool args',
        type: 'text',
        placeholder: '--verbose',
      },
    ],
  },
  keychainUnlock: {
    type: 'keychainUnlock',
    label: 'Keychain Unlock',
    description: 'Unlock a macOS keychain so codesign / xcodebuild don’t prompt.',
    color: '#f97316',
    icon: 'KeyRound',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'Keychain password (plaintext)',
        type: 'text',
        required: true,
        placeholder: '(matches the user login password by default)',
      },
      {
        name: 'keychain',
        label: 'Keychain path',
        type: 'text',
        placeholder: 'login.keychain-db (default)',
      },
      {
        name: 'unlockTimeoutSec',
        label: 'Re-lock after (seconds, optional)',
        type: 'number',
        placeholder: '3600',
      },
    ],
  },
  provisioningProfileInstall: {
    type: 'provisioningProfileInstall',
    label: 'Install Provisioning Profile',
    description:
      'Drop a .mobileprovision into ~/Library/MobileDevice/Provisioning Profiles (locally or remote).',
    color: '#a3e635',
    icon: 'BadgeCheck',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'profilePath',
        label: '.mobileprovision file (local — uploaded automatically when remote)',
        type: 'text',
        required: true,
        placeholder: 'signing/MyGame_AdHoc.mobileprovision',
      },
    ],
  },
  notarize: {
    type: 'notarize',
    label: 'Notarize',
    description:
      'Submit a .app/.dmg/.pkg/.zip to Apple notary service via xcrun notarytool. Required for macOS distribution outside the App Store.',
    color: '#f43f5e',
    icon: 'ShieldCheck',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'bundlePath',
        label: 'Bundle to notarize (.app, .dmg, .pkg, .zip)',
        type: 'text',
        required: true,
        placeholder: 'build/MyApp.dmg',
      },
      {
        name: 'authMethod',
        label: 'Auth method',
        type: 'select',
        options: ['apiKey', 'appleId'] as const,
        defaultValue: 'apiKey',
      },
      {
        name: 'apiKeyPath',
        label: 'AuthKey .p8 path (apiKey auth)',
        type: 'text',
        placeholder: '~/.appstoreconnect/private_keys/AuthKey_ABC123.p8',
      },
      {
        name: 'apiKeyId',
        label: 'API Key ID (apiKey auth)',
        type: 'text',
        placeholder: 'ABC123XYZ',
      },
      {
        name: 'apiIssuerId',
        label: 'API Issuer ID (apiKey auth)',
        type: 'text',
        placeholder: '57246542-…',
      },
      {
        name: 'appleId',
        label: 'Apple ID (appleId auth)',
        type: 'text',
        placeholder: 'developer@example.com',
      },
      {
        name: 'appPassword',
        label: 'App-specific password (appleId auth — plaintext)',
        type: 'text',
        placeholder: 'xxxx-xxxx-xxxx-xxxx',
      },
      {
        name: 'teamId',
        label: 'Team ID (appleId auth)',
        type: 'text',
        placeholder: 'AB12CDE34F',
      },
      {
        name: 'wait',
        label: 'Wait for Apple verdict before continuing',
        type: 'select',
        options: ['true', 'false'] as const,
        defaultValue: 'true',
      },
      {
        name: 'additionalArgs',
        label: 'Extra notarytool args',
        type: 'text',
        placeholder: '--verbose',
      },
    ],
  },
  dsymUpload: {
    type: 'dsymUpload',
    label: 'Upload dSYMs',
    description: 'Send debug symbols to a crash reporting service so stack traces resolve in production.',
    color: '#6366f1',
    icon: 'Bug',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'backend',
        label: 'Crash reporting backend',
        type: 'select',
        required: true,
        options: ['crashlytics', 'sentry', 'bugsnag'] as const,
        defaultValue: 'sentry',
      },
      {
        name: 'dsymPath',
        label: 'dSYM / .xcarchive / dSYM dir',
        type: 'text',
        required: true,
        placeholder: 'build/MyGame.xcarchive',
      },
      {
        name: 'googleServicePlistPath',
        label: 'GoogleService-Info.plist (Crashlytics only)',
        type: 'text',
        placeholder: 'GoogleService-Info.plist',
      },
      {
        name: 'uploadSymbolsBinary',
        label: 'Crashlytics upload-symbols path (optional)',
        type: 'text',
        placeholder: '(uses upload-symbols on PATH by default)',
      },
      {
        name: 'platform',
        label: 'Platform (Crashlytics only)',
        type: 'select',
        options: ['ios', 'macos', 'tvos', 'watchos'] as const,
        defaultValue: 'ios',
      },
      {
        name: 'sentryOrg',
        label: 'Sentry org (Sentry only)',
        type: 'text',
        placeholder: 'my-team',
      },
      {
        name: 'sentryProject',
        label: 'Sentry project (Sentry only)',
        type: 'text',
        placeholder: 'mygame-ios',
      },
      {
        name: 'sentryAuthToken',
        label: 'Sentry auth token (plaintext — passed via SENTRY_AUTH_TOKEN env)',
        type: 'text',
        placeholder: '…',
      },
      {
        name: 'bugsnagApiKey',
        label: 'Bugsnag API key (Bugsnag only)',
        type: 'text',
        placeholder: '32-char hex',
      },
      {
        name: 'bugsnagCliPath',
        label: 'bugsnag-cli path (optional)',
        type: 'text',
        placeholder: '(uses bugsnag-cli on PATH by default)',
      },
      {
        name: 'additionalArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: '--verbose',
      },
    ],
  },
  xcresultParse: {
    type: 'xcresultParse',
    label: 'Parse xcresult',
    description: 'Run xcresulttool against a .xcresult bundle and emit a "X/Y tests passed" summary.',
    color: '#84cc16',
    icon: 'ListChecks',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'bundlePath',
        label: 'Path to .xcresult bundle',
        type: 'text',
        required: true,
        placeholder: 'build/test-results.xcresult',
      },
      {
        name: 'failOnTestFailure',
        label: 'Fail step when any test failed',
        type: 'select',
        options: ['true', 'false'] as const,
        defaultValue: 'true',
      },
    ],
  },
  cocoapodsInstall: {
    type: 'cocoapodsInstall',
    label: 'CocoaPods Install',
    description: 'Run `pod install` (or `pod update`) to fetch CocoaPods dependencies.',
    color: '#ef4444',
    icon: 'Box',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'command',
        label: 'Command',
        type: 'select',
        options: ['install', 'update'] as const,
        defaultValue: 'install',
      },
      {
        name: 'repoUpdate',
        label: 'Pass --repo-update (slower, ensures fresh specs)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'useBundleExec',
        label: 'Prefix with `bundle exec`',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'cwd',
        label: 'Working dir (where Podfile lives)',
        type: 'text',
        placeholder: '. (defaults to project root)',
      },
      {
        name: 'additionalArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: '--verbose',
      },
    ],
  },
  swiftPackageResolve: {
    type: 'swiftPackageResolve',
    label: 'SPM Resolve',
    description: 'Pre-resolve Swift Package Manager dependencies via xcodebuild -resolvePackageDependencies.',
    color: '#fb923c',
    icon: 'Boxes',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'workspacePath',
        label: 'Workspace (.xcworkspace)',
        type: 'text',
        placeholder: 'MyGame.xcworkspace',
      },
      {
        name: 'projectPath',
        label: 'Project (.xcodeproj, used if no workspace)',
        type: 'text',
        placeholder: 'MyGame.xcodeproj',
      },
      {
        name: 'scheme',
        label: 'Scheme (optional — narrows resolution to one scheme)',
        type: 'text',
        placeholder: 'MyGame',
      },
      {
        name: 'clonedSourcePackagesDirPath',
        label: 'SourcePackages cache dir (optional)',
        type: 'text',
        placeholder: 'build/SourcePackages',
      },
      {
        name: 'additionalArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: '-quiet',
      },
    ],
  },
  fastlaneMatch: {
    type: 'fastlaneMatch',
    label: 'Fastlane Match',
    description:
      'Sync code-signing certs + provisioning profiles via fastlane match. Pair with keychainUnlock so the certs land in an unlocked keychain.',
    color: '#22c55e',
    icon: 'Wrench',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password (only for inline host)',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'matchType',
        label: 'Type',
        type: 'select',
        required: true,
        options: ['development', 'adhoc', 'appstore', 'enterprise', 'developer_id'] as const,
        defaultValue: 'appstore',
      },
      {
        name: 'appIdentifier',
        label: 'App identifier (comma-separated for multiple)',
        type: 'text',
        placeholder: 'com.example.MyGame',
      },
      {
        name: 'gitUrl',
        label: 'Match Git URL (or leave blank to use Matchfile)',
        type: 'text',
        placeholder: 'https://github.com/example/match-secrets.git',
      },
      {
        name: 'gitBranch',
        label: 'Match Git branch',
        type: 'text',
        placeholder: 'main',
      },
      {
        name: 'password',
        label: 'MATCH_PASSWORD (encrypts the match repo — plaintext)',
        type: 'text',
        placeholder: '…',
      },
      {
        name: 'keychainName',
        label: 'Target keychain (empty = login.keychain-db)',
        type: 'text',
        placeholder: 'login.keychain-db',
      },
      {
        name: 'keychainPassword',
        label: 'Keychain password (plaintext)',
        type: 'text',
        placeholder: '(only if keychain is locked)',
      },
      {
        name: 'readonly',
        label: 'Readonly mode (recommended for CI)',
        type: 'select',
        options: ['true', 'false'] as const,
        defaultValue: 'true',
      },
      {
        name: 'cwd',
        label: 'Working dir on the runner (where Matchfile lives)',
        type: 'text',
        placeholder: '. (defaults to project root on local runs)',
      },
      {
        name: 'additionalArgs',
        label: 'Extra fastlane args',
        type: 'text',
        placeholder: '--verbose',
      },
    ],
  },
  stapleNotarization: {
    type: 'stapleNotarization',
    label: 'Staple Notarization',
    description:
      'Embed the notarization ticket into a notarized bundle so Gatekeeper can verify it offline.',
    color: '#fb7185',
    icon: 'Stamp',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'bundlePath',
        label: 'Bundle that already passed notarization',
        type: 'text',
        required: true,
        placeholder: 'build/MyApp.dmg',
      },
    ],
  },
  artifact: {
    type: 'artifact',
    label: 'Artifact',
    description: 'Record build outputs (paths or globs) so they can be downloaded later.',
    color: '#facc15',
    icon: 'Package',
    fields: [
      {
        name: 'paths',
        label: 'Paths (one per line)',
        type: 'textarea',
        required: true,
        placeholder:
          'Builds/Linux/server.x86_64\nBuilds/Linux/server_Data/**\nartifacts/dist/**',
        help: 'A path can be a file, a directory (one level), or end with /** for recursive walk.',
      },
    ],
  },
  xcodeSelect: {
    type: 'xcodeSelect',
    label: 'Xcode Select',
    description: 'Switch the active Xcode toolchain via `xcode-select -s`. Local or via a saved Mac host.',
    color: '#38bdf8',
    icon: 'Wand2',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'xcodePath',
        label: 'Xcode .app bundle path',
        type: 'text',
        required: true,
        placeholder: '/Applications/Xcode_15.4.app',
        help: 'Passed to `sudo xcode-select -s`. The user must have passwordless sudo for xcode-select on the target host.',
      },
    ],
  },
  ensureGitStatusClean: {
    type: 'ensureGitStatusClean',
    label: 'Ensure Clean Tree',
    description: 'Pre-flight gate: fail the pipeline if `git status --porcelain` reports any modified or untracked paths.',
    color: '#f59e0b',
    icon: 'ShieldAlert',
    fields: [
      {
        name: 'hostId',
        label: 'Saved host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '. (defaults to project root)',
      },
    ],
  },
  incrementBuildNumber: {
    type: 'incrementBuildNumber',
    label: 'Increment Build #',
    description:
      'Bump CFBundleVersion via `agvtool` (auto-increment by 1 or set explicitly) or `PlistBuddy`.',
    color: '#22c55e',
    icon: 'Plus',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'mode',
        label: 'Mode',
        type: 'select',
        options: ['agvtool', 'plistBuddy'] as const,
        defaultValue: 'agvtool',
      },
      {
        name: 'versionString',
        label: 'Version (blank = agvtool next-version auto-bump)',
        type: 'text',
        placeholder: '42',
        help: 'Blank with mode=agvtool runs `next-version -all`. Required for plistBuddy.',
      },
      {
        name: 'plistPath',
        label: 'Info.plist path (plistBuddy only)',
        type: 'text',
        placeholder: 'MyApp/Info.plist',
      },
      {
        name: 'cwd',
        label: 'Working dir (must contain .xcodeproj for agvtool)',
        type: 'text',
        placeholder: '. (defaults to project root)',
      },
    ],
  },
  getBuildNumber: {
    type: 'getBuildNumber',
    label: 'Get Build #',
    description:
      'Read CFBundleVersion via `agvtool what-version -terse` or `PlistBuddy Print :CFBundleVersion`.',
    color: '#10b981',
    icon: 'Hash',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'mode',
        label: 'Mode',
        type: 'select',
        options: ['agvtool', 'plistBuddy'] as const,
        defaultValue: 'agvtool',
      },
      {
        name: 'plistPath',
        label: 'Info.plist path (plistBuddy only)',
        type: 'text',
        placeholder: 'MyApp/Info.plist',
      },
      {
        name: 'cwd',
        label: 'Working dir (must contain .xcodeproj for agvtool)',
        type: 'text',
        placeholder: '. (defaults to project root)',
      },
    ],
  },
  changelogFromGitCommits: {
    type: 'changelogFromGitCommits',
    label: 'Changelog From Git',
    description:
      'Generate release-note text from a commit range via `git log --pretty`. Feeds testflight whatToTest / App Store deliver release notes.',
    color: '#a855f7',
    icon: 'ScrollText',
    fields: [
      {
        name: 'hostId',
        label: 'Saved host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'user@host',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'fromRef',
        label: 'From ref (exclusive)',
        type: 'text',
        required: true,
        placeholder: 'v1.4.0',
      },
      {
        name: 'toRef',
        label: 'To ref (inclusive, default HEAD)',
        type: 'text',
        placeholder: 'HEAD',
      },
      {
        name: 'format',
        label: 'Format',
        type: 'select',
        options: ['subject', 'subject-body', 'oneline'] as const,
        defaultValue: 'subject',
      },
      {
        name: 'maxCommits',
        label: 'Max commits to include',
        type: 'number',
        placeholder: '1000',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '.',
      },
    ],
  },
  updateInfoPlist: {
    type: 'updateInfoPlist',
    label: 'Update Info.plist',
    description:
      'Set / Add / Delete a key in any plist via `/usr/libexec/PlistBuddy`. Common pre-build mutation for bundle id, version, endpoint URLs.',
    color: '#f59e0b',
    icon: 'FileCog',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'user@host',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'plistPath',
        label: 'Plist path',
        type: 'text',
        required: true,
        placeholder: 'MyApp/Info.plist',
      },
      {
        name: 'key',
        label: 'Key path (e.g. :CFBundleDisplayName)',
        type: 'text',
        required: true,
        placeholder: ':CFBundleDisplayName',
      },
      {
        name: 'operation',
        label: 'Operation',
        type: 'select',
        options: ['set', 'add-string', 'delete'] as const,
        defaultValue: 'set',
      },
      {
        name: 'value',
        label: 'Value (required for set / add-string)',
        type: 'text',
        placeholder: 'new value',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '.',
      },
    ],
  },
  swiftlint: {
    type: 'swiftlint',
    label: 'SwiftLint',
    description: 'Run swiftlint lint / fix / analyze with optional config + reporter selection.',
    color: '#10b981',
    icon: 'CodeXml',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'user@host',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'mode',
        label: 'Mode',
        type: 'select',
        options: ['lint', 'fix', 'analyze'] as const,
        defaultValue: 'lint',
      },
      {
        name: 'configFile',
        label: 'Config file path (.swiftlint.yml, optional)',
        type: 'text',
        placeholder: '.swiftlint.yml',
      },
      {
        name: 'paths',
        label: 'Paths (one per line, optional)',
        type: 'textarea',
        placeholder: 'Sources\nTests',
      },
      {
        name: 'strict',
        label: 'Treat warnings as errors (--strict)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'reporter',
        label: 'Reporter',
        type: 'select',
        options: ['xcode', 'json', 'junit', 'markdown', 'html', 'emoji'] as const,
        defaultValue: 'xcode',
      },
      {
        name: 'quiet',
        label: 'Quiet (suppress per-rule progress)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '.',
      },
    ],
  },
  swiftFormat: {
    type: 'swiftFormat',
    label: 'swift-format',
    description: 'Apple swift-format lint or in-place format with optional configuration.',
    color: '#0ea5e9',
    icon: 'AlignLeft',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'user@host',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'mode',
        label: 'Mode',
        type: 'select',
        options: ['lint', 'format'] as const,
        defaultValue: 'lint',
      },
      {
        name: 'configFile',
        label: 'Config file path (.swift-format, optional)',
        type: 'text',
        placeholder: '.swift-format',
      },
      {
        name: 'paths',
        label: 'Paths (one per line)',
        type: 'textarea',
        placeholder: 'Sources',
      },
      {
        name: 'recursive',
        label: 'Recursive (--recursive)',
        type: 'select',
        options: ['true', 'false'] as const,
        defaultValue: 'true',
      },
      {
        name: 'parallel',
        label: 'Parallel (--parallel)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '.',
      },
    ],
  },
  xcodebuildAnalyze: {
    type: 'xcodebuildAnalyze',
    label: 'xcodebuild Analyze',
    description: 'Run Apple Clang static analyzer via `xcrun xcodebuild analyze`.',
    color: '#0891b2',
    icon: 'Microscope',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'user@host',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'workspacePath',
        label: 'Workspace (.xcworkspace)',
        type: 'text',
        placeholder: 'MyApp.xcworkspace',
      },
      {
        name: 'projectPath',
        label: 'Project (.xcodeproj, used if no workspace)',
        type: 'text',
        placeholder: 'MyApp.xcodeproj',
      },
      {
        name: 'scheme',
        label: 'Scheme',
        type: 'text',
        required: true,
        placeholder: 'MyApp',
      },
      {
        name: 'configuration',
        label: 'Configuration',
        type: 'select',
        options: ['Debug', 'Release'] as const,
        defaultValue: 'Release',
      },
      {
        name: 'destination',
        label: 'Destination',
        type: 'text',
        placeholder: 'generic/platform=iOS',
      },
      {
        name: 'additionalArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: 'CODE_SIGNING_ALLOWED=NO',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '.',
      },
    ],
  },
  peripheryScan: {
    type: 'peripheryScan',
    label: 'Periphery Scan',
    description: 'Detect dead Swift code via `periphery scan`. Pair with strict mode to fail builds.',
    color: '#a855f7',
    icon: 'Search',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'user@host',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'workspacePath',
        label: 'Workspace (.xcworkspace)',
        type: 'text',
        placeholder: 'MyApp.xcworkspace',
      },
      {
        name: 'projectPath',
        label: 'Project (.xcodeproj, used if no workspace)',
        type: 'text',
        placeholder: 'MyApp.xcodeproj',
      },
      {
        name: 'schemes',
        label: 'Schemes (comma-separated)',
        type: 'text',
        placeholder: 'Free,Pro',
      },
      {
        name: 'targets',
        label: 'Targets (comma-separated)',
        type: 'text',
        placeholder: 'AppCore,AppUI',
      },
      {
        name: 'format',
        label: 'Output format',
        type: 'select',
        options: ['xcode', 'json', 'csv', 'github-actions', 'checkstyle'] as const,
        defaultValue: 'xcode',
      },
      {
        name: 'strict',
        label: 'Strict (treat unused as build errors)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'configFile',
        label: 'Config file (.periphery.yml, optional)',
        type: 'text',
        placeholder: '.periphery.yml',
      },
      {
        name: 'additionalArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: '--clean-build',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '.',
      },
    ],
  },
  slatherCoverage: {
    type: 'slatherCoverage',
    label: 'Slather Coverage',
    description: 'Generate coverage reports from .xcresult via the slather gem (HTML / JSON / Cobertura / Sonar / simple).',
    color: '#84cc16',
    icon: 'Percent',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'user@host',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'projectPath',
        label: 'Project (.xcodeproj)',
        type: 'text',
        required: true,
        placeholder: 'MyApp.xcodeproj',
      },
      {
        name: 'workspacePath',
        label: 'Workspace (.xcworkspace, optional)',
        type: 'text',
        placeholder: 'MyApp.xcworkspace',
      },
      {
        name: 'scheme',
        label: 'Scheme',
        type: 'text',
        placeholder: 'MyApp',
      },
      {
        name: 'format',
        label: 'Output format',
        type: 'select',
        options: ['html', 'json', 'cobertura', 'simple', 'sonarqube'] as const,
        defaultValue: 'html',
      },
      {
        name: 'outputDirectory',
        label: 'Output directory',
        type: 'text',
        placeholder: 'coverage_html',
      },
      {
        name: 'buildDirectory',
        label: 'Build directory (DerivedData)',
        type: 'text',
        placeholder: 'build',
      },
      {
        name: 'additionalArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: '--ignore */Pods/*',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '.',
      },
    ],
  },
  xcovGate: {
    type: 'xcovGate',
    label: 'xcov Coverage Gate',
    description: 'Parse xcov coverage and fail the build below a minimum percentage.',
    color: '#facc15',
    icon: 'Gauge',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'user@host',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'workspacePath',
        label: 'Workspace (.xcworkspace)',
        type: 'text',
        placeholder: 'MyApp.xcworkspace',
      },
      {
        name: 'projectPath',
        label: 'Project (.xcodeproj, used if no workspace)',
        type: 'text',
        placeholder: 'MyApp.xcodeproj',
      },
      {
        name: 'scheme',
        label: 'Scheme',
        type: 'text',
        required: true,
        placeholder: 'MyApp',
      },
      {
        name: 'minimumCoveragePercentage',
        label: 'Minimum coverage percentage (0 = no gate)',
        type: 'number',
        defaultValue: 0,
      },
      {
        name: 'outputDirectory',
        label: 'Output directory',
        type: 'text',
        placeholder: 'xcov_report',
      },
      {
        name: 'includeTargets',
        label: 'Include targets (comma-separated)',
        type: 'text',
        placeholder: 'AppCore,AppUI',
      },
      {
        name: 'excludeTargets',
        label: 'Exclude targets (comma-separated)',
        type: 'text',
        placeholder: 'AppTests',
      },
      {
        name: 'jsonReport',
        label: 'JSON report',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'markdownReport',
        label: 'Markdown report',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'additionalArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: '--ignore_file_path .xcovignore',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '.',
      },
    ],
  },
  resign: {
    type: 'resign',
    label: 'Resign IPA',
    description: 'Re-codesign an existing .ipa / .app via `fastlane sigh resign` (requires unlocked keychain — chain after keychainUnlock).',
    color: '#ec4899',
    icon: 'PenTool',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'user@host',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'ipaPath',
        label: 'IPA / .app path',
        type: 'text',
        required: true,
        placeholder: 'build/MyApp.ipa',
      },
      {
        name: 'signingIdentity',
        label: 'Signing identity (full keychain string)',
        type: 'text',
        required: true,
        placeholder: 'Apple Distribution: Acme Corp (ABC123XYZ4)',
      },
      {
        name: 'provisioningProfile',
        label: 'Provisioning profile path',
        type: 'text',
        required: true,
        placeholder: 'signing/AppStore.mobileprovision',
      },
      {
        name: 'bundleId',
        label: 'Bundle ID override (optional)',
        type: 'text',
        placeholder: 'com.acme.app',
      },
      {
        name: 'displayName',
        label: 'CFBundleDisplayName override (optional)',
        type: 'text',
        placeholder: 'Acme',
      },
      {
        name: 'entitlements',
        label: 'Entitlements .plist (optional)',
        type: 'text',
        placeholder: 'signing/MyApp.entitlements',
      },
      {
        name: 'keychainPath',
        label: 'Keychain path (optional)',
        type: 'text',
        placeholder: '~/Library/Keychains/login.keychain-db',
      },
      {
        name: 'additionalArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: '--verbose',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '.',
      },
    ],
  },
  snapshot: {
    type: 'snapshot',
    label: 'Snapshot',
    description: 'Drive `fastlane snapshot` to capture localized screenshots across simulator devices via UI Tests.',
    color: '#f97316',
    icon: 'Camera',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'user@host',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'outputDirectory',
        label: 'Output directory',
        type: 'text',
        placeholder: 'screenshots',
      },
      {
        name: 'scheme',
        label: 'Scheme (optional, may live in Snapfile)',
        type: 'text',
        placeholder: 'MyAppUITests',
      },
      {
        name: 'workspacePath',
        label: 'Workspace (.xcworkspace, optional)',
        type: 'text',
        placeholder: 'MyApp.xcworkspace',
      },
      {
        name: 'projectPath',
        label: 'Project (.xcodeproj, optional)',
        type: 'text',
        placeholder: 'MyApp.xcodeproj',
      },
      {
        name: 'devices',
        label: 'Devices (comma-separated)',
        type: 'text',
        placeholder: 'iPhone 16 Pro,iPad Pro',
      },
      {
        name: 'languages',
        label: 'Languages (comma-separated)',
        type: 'text',
        placeholder: 'en-US,fr-FR',
      },
      {
        name: 'launchArguments',
        label: 'Launch arguments (one per line)',
        type: 'textarea',
        placeholder: '-StateA\n-StateB',
      },
      {
        name: 'iosVersion',
        label: 'iOS version (optional)',
        type: 'text',
        placeholder: '18.0',
      },
      {
        name: 'clearPreviousScreenshots',
        label: 'Clear previous screenshots',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'outputSimulatorLogs',
        label: 'Capture simulator logs',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'additionalArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: '--verbose',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '.',
      },
    ],
  },
  frameit: {
    type: 'frameit',
    label: 'Frameit',
    description: 'Frame raw screenshots with downloaded device chrome via `fastlane frameit`.',
    color: '#fb923c',
    icon: 'Frame',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'user@host',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'pathToScreenshots',
        label: 'Path to screenshots dir',
        type: 'text',
        placeholder: './screenshots',
      },
      {
        name: 'colorFlag',
        label: 'Device color',
        type: 'select',
        options: ['none', 'silver', 'gold', 'rose-gold', 'space-gray'] as const,
        defaultValue: 'none',
      },
      {
        name: 'force',
        label: 'Overwrite existing framed images',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'useLegacyIphone5s',
        label: 'Use legacy iPhone 5s frames',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'usePlatform',
        label: 'Platform (IOS / ANDROID / ANY)',
        type: 'text',
        placeholder: 'IOS',
      },
      {
        name: 'additionalArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: '--verbose',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '.',
      },
    ],
  },
  gradleBuild: {
    type: 'gradleBuild',
    label: 'Gradle Build',
    description: 'Run ./gradlew (gradlew.bat on Windows) to produce an APK or AAB.',
    color: '#84cc16',
    icon: 'Hammer',
    fields: [
      {
        name: 'output',
        label: 'Output type',
        type: 'select',
        required: true,
        options: ['apk', 'aab', 'custom'] as const,
        defaultValue: 'apk',
        help: 'apk → assemble<Variant>, aab → bundle<Variant>, custom → use the gradleTask field.',
      },
      {
        name: 'variant',
        label: 'Variant (capitalized)',
        type: 'text',
        placeholder: 'Release',
        defaultValue: 'Release',
        help: 'Case matters — gradle generates assembleRelease, not assemblerelease.',
      },
      {
        name: 'module',
        label: 'Module path',
        type: 'text',
        placeholder: ':app',
        defaultValue: ':app',
      },
      {
        name: 'gradleTask',
        label: 'Custom gradle task (only when output=custom)',
        type: 'text',
        placeholder: ':app:assembleStagingDebug',
      },
      {
        name: 'gradleArgs',
        label: 'Extra gradle args',
        type: 'text',
        placeholder: '--info --no-daemon',
      },
      {
        name: 'cwd',
        label: 'Working dir (relative — gradlew location)',
        type: 'text',
        placeholder: '. (defaults to project root)',
      },
      {
        name: 'registerArtifact',
        label: 'Auto-register produced APK/AAB as artifact',
        type: 'select',
        options: ['true', 'false'] as const,
        defaultValue: 'true',
      },
    ],
  },
  adbConnect: {
    type: 'adbConnect',
    label: 'ADB Connect',
    description: 'Pair a Wi-Fi-debugging device with the adb server (adb connect ip:port).',
    color: '#22c55e',
    icon: 'Wifi',
    fields: [
      {
        name: 'address',
        label: 'Device address (ip:port)',
        type: 'text',
        required: true,
        placeholder: '192.168.1.100:5555',
        help: 'Device must already be authorized — pair via USB once or use adb pair on Android 11+.',
      },
      {
        name: 'adbPath',
        label: 'adb executable (override if not on PATH)',
        type: 'text',
        placeholder: 'adb',
      },
    ],
  },
  adbInstall: {
    type: 'adbInstall',
    label: 'ADB Install',
    description: 'Install an APK onto a connected device (adb install -r).',
    color: '#16a34a',
    icon: 'Download',
    fields: [
      {
        name: 'apkPath',
        label: 'APK path (relative or absolute)',
        type: 'text',
        required: true,
        placeholder: 'app/build/outputs/apk/release/app-release.apk',
      },
      {
        name: 'serial',
        label: 'Device serial (leave blank for single-device setups)',
        type: 'text',
        placeholder: 'emulator-5554 or 192.168.1.100:5555',
      },
      {
        name: 'replace',
        label: 'Replace existing install (-r)',
        type: 'select',
        options: ['true', 'false'] as const,
        defaultValue: 'true',
      },
      {
        name: 'allowDowngrade',
        label: 'Allow version downgrade (-d)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'allowTest',
        label: 'Allow test packages (-t)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'adbPath',
        label: 'adb executable (override if not on PATH)',
        type: 'text',
        placeholder: 'adb',
      },
    ],
  },
  adbShellLaunch: {
    type: 'adbShellLaunch',
    label: 'ADB Launch App',
    description: 'Start an app on the device (adb shell am start -n pkg/.Activity).',
    color: '#15803d',
    icon: 'Play',
    fields: [
      {
        name: 'packageName',
        label: 'Package name',
        type: 'text',
        required: true,
        placeholder: 'com.example.app',
      },
      {
        name: 'activity',
        label: 'Activity (.MainActivity or fully qualified — blank = default launcher)',
        type: 'text',
        placeholder: '.MainActivity',
      },
      {
        name: 'serial',
        label: 'Device serial (leave blank for single-device setups)',
        type: 'text',
        placeholder: 'emulator-5554',
      },
      {
        name: 'waitForLaunch',
        label: 'Wait for launch to complete (-W)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'adbPath',
        label: 'adb executable (override if not on PATH)',
        type: 'text',
        placeholder: 'adb',
      },
    ],
  },
  adbLogcat: {
    type: 'adbLogcat',
    label: 'ADB Logcat',
    description: 'Capture logcat for N seconds and save the output as a build artifact.',
    color: '#65a30d',
    icon: 'ScrollText',
    fields: [
      {
        name: 'durationSec',
        label: 'Duration (seconds)',
        type: 'number',
        defaultValue: 30,
      },
      {
        name: 'serial',
        label: 'Device serial (leave blank for single-device setups)',
        type: 'text',
        placeholder: 'emulator-5554',
      },
      {
        name: 'filter',
        label: 'Logcat filter spec (optional)',
        type: 'text',
        placeholder: '*:E  or  MyTag:D *:S',
      },
      {
        name: 'outputPath',
        label: 'Output file (relative to project root)',
        type: 'text',
        placeholder: 'logcat-<buildId>.txt (default)',
      },
      {
        name: 'clearFirst',
        label: 'Clear ring buffer before capture (-c)',
        type: 'select',
        options: ['true', 'false'] as const,
        defaultValue: 'true',
      },
      {
        name: 'registerArtifact',
        label: 'Register output as build artifact',
        type: 'select',
        options: ['true', 'false'] as const,
        defaultValue: 'true',
      },
      {
        name: 'adbPath',
        label: 'adb executable (override if not on PATH)',
        type: 'text',
        placeholder: 'adb',
      },
    ],
  },
  aiPrompt: {
    type: 'aiPrompt',
    label: 'AI Prompt',
    description: 'Run a non-interactive prompt through claude / codex / aider / gemini / custom CLI.',
    color: '#ec4899',
    icon: 'Sparkles',
    fields: [
      {
        name: 'tool',
        label: 'Tool',
        type: 'select',
        required: true,
        options: ['claude', 'codex', 'aider', 'gemini', 'custom'] as const,
        defaultValue: 'claude',
      },
      {
        name: 'command',
        label: 'Custom command (only when tool=custom)',
        type: 'text',
        placeholder: 'mycli --flag',
      },
      {
        name: 'prompt',
        label: 'Prompt',
        type: 'textarea',
        required: true,
        placeholder: 'Fix the failing test in src/utils.ts so that pnpm test passes.',
      },
      {
        name: 'cwd',
        label: 'Working dir (relative)',
        type: 'text',
        placeholder: '. (defaults to project root)',
      },
      {
        name: 'allowFailure',
        label: 'Allow failure (continue on non-zero exit)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
    ],
  },
  teamsNotify: {
    type: 'teamsNotify',
    label: 'Teams Notify',
    description: 'Post a message to a Microsoft Teams incoming webhook (legacy connector or Power Automate workflow).',
    color: '#7c3aed',
    icon: 'MessageSquareMore',
    fields: [
      {
        name: 'webhookUrl',
        label: 'Webhook URL',
        type: 'text',
        required: true,
        placeholder: 'https://outlook.office.com/webhook/.../IncomingWebhook/...',
      },
      {
        name: 'format',
        label: 'Payload format',
        type: 'select',
        options: ['simple', 'messageCard', 'raw'] as const,
        defaultValue: 'simple',
        help: 'simple = { text:"…" } (works for both legacy + workflow). messageCard adds title/themeColor (legacy only). raw forwards the JSON in "text" verbatim — use for Adaptive Cards.',
      },
      {
        name: 'title',
        label: 'Title (messageCard only)',
        type: 'text',
        placeholder: 'Build #42 succeeded',
      },
      {
        name: 'themeColor',
        label: 'Theme color hex (messageCard only, no #)',
        type: 'text',
        placeholder: '00FF00',
      },
      {
        name: 'text',
        label: 'Message text (or raw JSON when format=raw)',
        type: 'textarea',
        required: true,
        placeholder: '✅ Build #42 succeeded',
      },
    ],
  },
  emailNotify: {
    type: 'emailNotify',
    label: 'Email Notify',
    description: 'Send a transactional email via SMTP (uses nodemailer at runtime).',
    color: '#0d9488',
    icon: 'Mail',
    fields: [
      {
        name: 'smtpHost',
        label: 'SMTP host',
        type: 'text',
        required: true,
        placeholder: 'smtp.gmail.com',
      },
      {
        name: 'smtpPort',
        label: 'SMTP port (default 587)',
        type: 'number',
        placeholder: '587',
      },
      {
        name: 'smtpSecure',
        label: 'TLS-on-connect (auto-detected from port)',
        type: 'select',
        options: ['', 'true', 'false'] as const,
        defaultValue: '',
        help: 'Empty = auto (port 465 → TLS, else STARTTLS). Override only for non-standard providers.',
      },
      {
        name: 'smtpUser',
        label: 'SMTP user',
        type: 'text',
        required: true,
        placeholder: 'ci@example.com',
      },
      {
        name: 'smtpPassword',
        label: 'SMTP password / app password',
        type: 'text',
        required: true,
        placeholder: '(encrypted at rest)',
        help: 'For Gmail / O365: use an app-specific password. The value is stored encrypted on the server (master.key under ~/.buildpilot/).',
      },
      {
        name: 'from',
        label: 'From',
        type: 'text',
        required: true,
        placeholder: '"BuildPilot CI" <ci@example.com>',
      },
      {
        name: 'to',
        label: 'To (comma / semicolon / whitespace separated)',
        type: 'text',
        required: true,
        placeholder: 'team@example.com',
      },
      {
        name: 'cc',
        label: 'Cc (optional)',
        type: 'text',
        placeholder: 'lead@example.com',
      },
      {
        name: 'bcc',
        label: 'Bcc (optional)',
        type: 'text',
        placeholder: 'audit@example.com',
      },
      {
        name: 'subject',
        label: 'Subject',
        type: 'text',
        required: true,
        placeholder: 'Build #42 ok',
      },
      {
        name: 'bodyText',
        label: 'Body (plain text)',
        type: 'textarea',
        placeholder: 'Build green. Logs at https://buildpilot.example.com/builds/42',
      },
      {
        name: 'bodyHtml',
        label: 'Body (HTML — optional, multipart with text)',
        type: 'textarea',
        placeholder: '<h1>Build green</h1>',
      },
    ],
  },
  appStoreConnectApi: {
    type: 'appStoreConnectApi',
    label: 'ASC API (raw)',
    description: 'Sign an ES256 JWT and call any App Store Connect API endpoint with custom JSON body.',
    color: '#0f172a',
    icon: 'Code2',
    fields: [
      ...ASC_CRED_FIELDS,
      {
        name: 'method',
        label: 'HTTP method',
        type: 'select',
        options: ['GET', 'POST', 'PATCH', 'DELETE'] as const,
        defaultValue: 'GET',
      },
      {
        name: 'path',
        label: 'API path (under api.appstoreconnect.apple.com)',
        type: 'text',
        required: true,
        placeholder: '/v1/apps',
      },
      {
        name: 'queryJson',
        label: 'Query params (JSON object — optional)',
        type: 'textarea',
        placeholder: '{"filter[bundleId]":"com.example.app","limit":1}',
      },
      {
        name: 'bodyJson',
        label: 'Request body (JSON — optional)',
        type: 'textarea',
        placeholder: '{"data":{"type":"betaBuildLocalizations","attributes":{"whatsNew":"Bug fixes"}}}',
      },
    ],
  },
  testflightSetWhatToTest: {
    type: 'testflightSetWhatToTest',
    label: 'TestFlight: Set "What to Test"',
    description: 'Set the per-build TestFlight "What to Test" notes via App Store Connect API.',
    color: '#0284c7',
    icon: 'PenLine',
    fields: [
      ...ASC_CRED_FIELDS,
      {
        name: 'buildId',
        label: 'Build id (UUID — optional, omit to look up)',
        type: 'text',
        placeholder: '(blank → look up by appBundleId + version + buildNumber)',
      },
      {
        name: 'appBundleId',
        label: 'App bundle id (lookup mode)',
        type: 'text',
        placeholder: 'com.example.app',
      },
      {
        name: 'version',
        label: 'Marketing version (lookup mode)',
        type: 'text',
        placeholder: '1.4.0',
      },
      {
        name: 'buildNumber',
        label: 'Build number (lookup mode)',
        type: 'text',
        placeholder: '42',
      },
      {
        name: 'locale',
        label: 'Locale (BCP-47)',
        type: 'text',
        placeholder: 'en-US (default)',
      },
      {
        name: 'whatsNew',
        label: 'What to Test',
        type: 'textarea',
        required: true,
        placeholder: '- Fixed crash on launch\n- Improved battery life',
      },
    ],
  },
  testflightPublicLink: {
    type: 'testflightPublicLink',
    label: 'TestFlight: Public Link',
    description: 'Find or create a public-enabled BetaGroup, attach a build, and read the public TestFlight link.',
    color: '#06b6d4',
    icon: 'Link',
    fields: [
      ...ASC_CRED_FIELDS,
      {
        name: 'appBundleId',
        label: 'App bundle id',
        type: 'text',
        required: true,
        placeholder: 'com.example.app',
      },
      {
        name: 'groupName',
        label: 'BetaGroup name',
        type: 'text',
        placeholder: 'Public (default)',
      },
      {
        name: 'buildId',
        label: 'Build id (optional — attach this build)',
        type: 'text',
        placeholder: '(omit to just fetch the link)',
      },
    ],
  },
  testflightManage: {
    type: 'testflightManage',
    label: 'TestFlight: Manage Testers',
    description: 'Invite / remove / list TestFlight testers + add to / remove from BetaGroups.',
    color: '#0d9488',
    icon: 'Users',
    fields: [
      ...ASC_CRED_FIELDS,
      {
        name: 'action',
        label: 'Action',
        type: 'select',
        required: true,
        options: ['inviteTester', 'removeTester', 'listTesters', 'addToGroup', 'removeFromGroup'] as const,
        defaultValue: 'listTesters',
      },
      {
        name: 'appBundleId',
        label: 'App bundle id (most actions)',
        type: 'text',
        placeholder: 'com.example.app',
      },
      {
        name: 'testerEmail',
        label: 'Tester email',
        type: 'text',
        placeholder: 'tester@example.com',
      },
      {
        name: 'testerFirstName',
        label: 'Tester first name (invite)',
        type: 'text',
        placeholder: 'Alice',
      },
      {
        name: 'testerLastName',
        label: 'Tester last name (invite)',
        type: 'text',
        placeholder: 'Tester',
      },
      {
        name: 'groupName',
        label: 'BetaGroup name (group actions / optional invite)',
        type: 'text',
        placeholder: 'Internal',
      },
    ],
  },
  appStorePrecheck: {
    type: 'appStorePrecheck',
    label: 'App Store: Precheck',
    description: 'Run `fastlane precheck` to lint App Store metadata before submission.',
    color: '#65a30d',
    icon: 'ShieldCheck',
    fields: [
      ...REMOTE_HOST_FIELDS,
      {
        name: 'appIdentifier',
        label: 'App identifier',
        type: 'text',
        required: true,
        placeholder: 'com.example.app',
      },
      {
        name: 'username',
        label: 'Apple ID',
        type: 'text',
        placeholder: 'dev@example.com',
      },
      {
        name: 'teamId',
        label: 'Team ID',
        type: 'text',
        placeholder: 'AB12CDE34F',
      },
      {
        name: 'includeInAppPurchases',
        label: 'Include IAPs in lint',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'defaultRule',
        label: 'Default rule level (warn / error / skip)',
        type: 'select',
        options: ['', 'warn', 'error', 'skip'] as const,
        defaultValue: '',
      },
      {
        name: 'additionalArgs',
        label: 'Extra fastlane args',
        type: 'text',
        placeholder: '--free_stuff_in_iap true',
      },
      {
        name: 'cwd',
        label: 'Working dir',
        type: 'text',
        placeholder: '. (project root by default)',
      },
    ],
  },
  appStoreCreate: {
    type: 'appStoreCreate',
    label: 'App Store: Create App',
    description: 'Bootstrap a new app on App Store Connect (replaces fastlane produce).',
    color: '#a855f7',
    icon: 'PlusSquare',
    fields: [
      ...ASC_CRED_FIELDS,
      {
        name: 'bundleId',
        label: 'Bundle ID',
        type: 'text',
        required: true,
        placeholder: 'com.example.app',
      },
      {
        name: 'name',
        label: 'App name',
        type: 'text',
        required: true,
        placeholder: 'My App',
      },
      {
        name: 'sku',
        label: 'SKU',
        type: 'text',
        required: true,
        placeholder: 'MYAPP-001',
      },
      {
        name: 'primaryLocale',
        label: 'Primary locale',
        type: 'text',
        required: true,
        placeholder: 'en-US',
      },
      {
        name: 'platform',
        label: 'BundleId platform (when registering)',
        type: 'select',
        options: ['IOS', 'MAC_OS', 'UNIVERSAL'] as const,
        defaultValue: 'IOS',
      },
      {
        name: 'platforms',
        label: 'App platforms (comma-sep, e.g. IOS,MAC_OS)',
        type: 'text',
        placeholder: 'IOS',
      },
      {
        name: 'registerBundleId',
        label: 'Register bundleId on Dev Portal if missing',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
    ],
  },
  appStoreUpload: {
    type: 'appStoreUpload',
    label: 'App Store: Upload (deliver)',
    description: 'Upload the .ipa + metadata + screenshots via `fastlane deliver`. Optionally submits for review.',
    color: '#3b82f6',
    icon: 'Upload',
    fields: [
      ...REMOTE_HOST_FIELDS,
      {
        name: 'appIdentifier',
        label: 'App identifier',
        type: 'text',
        required: true,
        placeholder: 'com.example.app',
      },
      {
        name: 'ipaPath',
        label: '.ipa path',
        type: 'text',
        placeholder: 'build/MyApp.ipa',
      },
      {
        name: 'metadataPath',
        label: 'Metadata dir',
        type: 'text',
        placeholder: 'fastlane/metadata',
      },
      {
        name: 'screenshotsPath',
        label: 'Screenshots dir',
        type: 'text',
        placeholder: 'fastlane/screenshots',
      },
      {
        name: 'username',
        label: 'Apple ID',
        type: 'text',
        placeholder: 'dev@example.com',
      },
      {
        name: 'teamId',
        label: 'Team ID',
        type: 'text',
        placeholder: 'AB12CDE34F',
      },
      {
        name: 'skipBinaryUpload',
        label: 'Skip binary upload',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'skipMetadata',
        label: 'Skip metadata',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'skipScreenshots',
        label: 'Skip screenshots',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'submitForReview',
        label: 'Submit for review',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'automaticRelease',
        label: 'Automatic release after approval',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'force',
        label: 'Force (skip metadata-changes confirm)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'true',
      },
      {
        name: 'additionalArgs',
        label: 'Extra fastlane args',
        type: 'text',
      },
      {
        name: 'cwd',
        label: 'Working dir',
        type: 'text',
        placeholder: '. (project root by default)',
      },
    ],
  },
  buildAppGym: {
    type: 'buildAppGym',
    label: 'Build App (gym)',
    description: '`fastlane gym` — archive + export + xcpretty in one shot. Replaces the xcodebuild archive → exportArchive chain.',
    color: '#ea580c',
    icon: 'Hammer',
    fields: [
      ...REMOTE_HOST_FIELDS,
      {
        name: 'workspacePath',
        label: 'Workspace (.xcworkspace)',
        type: 'text',
        placeholder: 'MyApp.xcworkspace',
      },
      {
        name: 'projectPath',
        label: 'Project (.xcodeproj — used if no workspace)',
        type: 'text',
        placeholder: 'MyApp.xcodeproj',
      },
      {
        name: 'scheme',
        label: 'Scheme',
        type: 'text',
        required: true,
        placeholder: 'MyApp',
      },
      {
        name: 'configuration',
        label: 'Configuration',
        type: 'text',
        placeholder: 'Release',
      },
      {
        name: 'exportMethod',
        label: 'Export method',
        type: 'select',
        options: ['app-store', 'ad-hoc', 'enterprise', 'development', 'developer-id', 'mac-application'] as const,
        defaultValue: 'app-store',
      },
      {
        name: 'exportOptionsPlist',
        label: 'ExportOptions.plist',
        type: 'text',
        placeholder: 'signing/ExportOptions.plist',
      },
      {
        name: 'outputDirectory',
        label: 'Output dir',
        type: 'text',
        placeholder: 'build/ipa',
      },
      {
        name: 'outputName',
        label: 'Output filename (without ext)',
        type: 'text',
        placeholder: 'MyApp-1.4.0',
      },
      {
        name: 'cleanBeforeBuild',
        label: 'Clean before build',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'silent',
        label: 'Silent (suppress xcpretty)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'includeSymbols',
        label: 'Include dSYMs in IPA',
        type: 'select',
        options: ['true', 'false'] as const,
        defaultValue: 'true',
      },
      {
        name: 'includeBitcode',
        label: 'Include bitcode',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'skipArchive',
        label: 'Skip archive (assume already archived)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'skipPackageIpa',
        label: 'Skip IPA packaging',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'additionalArgs',
        label: 'Extra fastlane args',
        type: 'text',
        placeholder: '--xcargs OTHER_SWIFT_FLAGS=-D=DEBUG',
      },
      {
        name: 'cwd',
        label: 'Working dir',
        type: 'text',
        placeholder: '. (project root by default)',
      },
    ],
  },
  pushCertificate: {
    type: 'pushCertificate',
    label: 'APNs Push Certificate (pem)',
    description: 'Generate / refresh APNs production / dev / website push certs via `fastlane pem`.',
    color: '#dc2626',
    icon: 'Bell',
    fields: [
      ...REMOTE_HOST_FIELDS,
      {
        name: 'appIdentifier',
        label: 'App identifier',
        type: 'text',
        required: true,
        placeholder: 'com.example.app',
      },
      {
        name: 'username',
        label: 'Apple ID',
        type: 'text',
        placeholder: 'dev@example.com',
      },
      {
        name: 'teamId',
        label: 'Team ID',
        type: 'text',
        placeholder: 'AB12CDE34F',
      },
      {
        name: 'development',
        label: 'Development cert (default: production)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'generateP12',
        label: 'Generate .p12 in addition to .pem',
        type: 'select',
        options: ['true', 'false'] as const,
        defaultValue: 'true',
      },
      {
        name: 'password',
        label: '.p12 password',
        type: 'text',
        placeholder: '(encrypted at rest)',
      },
      {
        name: 'outputPath',
        label: 'Output dir',
        type: 'text',
        placeholder: '.',
      },
      {
        name: 'force',
        label: 'Regenerate even if cert is still valid',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'activeDaysLimit',
        label: 'Renew if expires within N days',
        type: 'number',
        placeholder: '30',
      },
      {
        name: 'additionalArgs',
        label: 'Extra fastlane args',
        type: 'text',
      },
      {
        name: 'cwd',
        label: 'Working dir',
        type: 'text',
      },
    ],
  },
  certManage: {
    type: 'certManage',
    label: 'Signing Cert (cert)',
    description: '`fastlane cert` — signing certificate CRUD. Backstop when not using fastlane match.',
    color: '#9333ea',
    icon: 'Award',
    fields: [
      ...REMOTE_HOST_FIELDS,
      {
        name: 'development',
        label: 'Development cert (default: production)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'appIdentifier',
        label: 'App identifier (optional, scopes the cert)',
        type: 'text',
        placeholder: 'com.example.app',
      },
      {
        name: 'username',
        label: 'Apple ID',
        type: 'text',
        placeholder: 'dev@example.com',
      },
      {
        name: 'teamId',
        label: 'Team ID',
        type: 'text',
        placeholder: 'AB12CDE34F',
      },
      {
        name: 'outputPath',
        label: 'Output dir',
        type: 'text',
      },
      {
        name: 'keychainPath',
        label: 'Keychain path',
        type: 'text',
        placeholder: 'login.keychain-db',
      },
      {
        name: 'keychainPassword',
        label: 'Keychain password',
        type: 'text',
      },
      {
        name: 'platform',
        label: 'Platform',
        type: 'select',
        options: ['ios', 'macos', 'catalyst'] as const,
        defaultValue: 'ios',
      },
      {
        name: 'force',
        label: 'Regenerate cert',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'additionalArgs',
        label: 'Extra fastlane args',
        type: 'text',
      },
      {
        name: 'cwd',
        label: 'Working dir',
        type: 'text',
      },
    ],
  },
  registerDevices: {
    type: 'registerDevices',
    label: 'Register Devices',
    description: 'Add device UDIDs to the Apple Developer Portal so ad-hoc / dev profiles include them.',
    color: '#16a34a',
    icon: 'Smartphone',
    fields: [
      ...ASC_CRED_FIELDS,
      {
        name: 'platform',
        label: 'Platform',
        type: 'select',
        options: ['IOS', 'MAC_OS'] as const,
        defaultValue: 'IOS',
      },
      {
        name: 'udids',
        label: 'UDIDs (one "Name=UDID" per line, or just UDID)',
        type: 'textarea',
        required: true,
        placeholder: `# Comments allowed\nAlice's iPhone=00008101-001A2B3C4D5E6F70\nBob's iPad=ABCDEF1234567890ABCDEF1234567890ABCDEFAA`,
      },
    ],
  },
  sigh: {
    type: 'sigh',
    label: 'Provisioning (sigh)',
    description: '`fastlane sigh` — download / renew / repair / manage provisioning profiles.',
    color: '#ca8a04',
    icon: 'BadgePlus',
    fields: [
      ...REMOTE_HOST_FIELDS,
      {
        name: 'action',
        label: 'Action',
        type: 'select',
        options: ['download', 'renew', 'repair', 'manage'] as const,
        defaultValue: 'download',
      },
      {
        name: 'profileType',
        label: 'Profile type',
        type: 'select',
        options: ['appstore', 'adhoc', 'development', 'developer_id'] as const,
        defaultValue: 'appstore',
      },
      {
        name: 'appIdentifier',
        label: 'App identifier',
        type: 'text',
        placeholder: 'com.example.app',
      },
      {
        name: 'username',
        label: 'Apple ID',
        type: 'text',
        placeholder: 'dev@example.com',
      },
      {
        name: 'teamId',
        label: 'Team ID',
        type: 'text',
      },
      {
        name: 'outputPath',
        label: 'Output dir',
        type: 'text',
      },
      {
        name: 'force',
        label: 'Force regenerate (renew/repair)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'skipInstall',
        label: 'Skip install (just download)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'platform',
        label: 'Platform',
        type: 'select',
        options: ['ios', 'tvos', 'macos'] as const,
        defaultValue: 'ios',
      },
      {
        name: 'additionalArgs',
        label: 'Extra fastlane args',
        type: 'text',
      },
      {
        name: 'cwd',
        label: 'Working dir',
        type: 'text',
      },
    ],
  },
};

export const STEP_TYPES: readonly StepType[] = Object.keys(STEP_DEFINITIONS) as StepType[];

export function getStepDefinition(type: StepType): StepDefinition {
  return STEP_DEFINITIONS[type];
}

export type StepCategory =
  | 'git'
  | 'build'
  | 'notify'
  | 'upload'
  | 'remote'
  | 'iosBuild'
  | 'iosSigning'
  | 'iosDistribute'
  | 'iosVersioning'
  | 'iosQuality'
  | 'iosScreenshots'
  | 'android';

export interface StepCategoryGroup {
  key: StepCategory;
  label: string;
  types: readonly StepType[];
}

// Order here drives palette display order. Each StepType must appear in
// exactly one group — see the assertion at the bottom of the file.
export const STEP_CATEGORIES: readonly StepCategoryGroup[] = [
  {
    key: 'git',
    label: 'Git',
    types: ['checkout', 'pull', 'gitMerge', 'ensureGitStatusClean', 'changelogFromGitCommits'],
  },
  {
    key: 'build',
    label: 'Build',
    types: ['shell', 'unityBatch', 'aiPrompt'],
  },
  {
    key: 'notify',
    label: 'Notifications',
    types: ['slackNotify', 'discordNotify', 'telegramNotify', 'teamsNotify', 'emailNotify', 'httpRequest'],
  },
  {
    key: 'upload',
    label: 'Artifacts & Upload',
    types: ['artifact', 's3Upload', 'sftpUpload', 'dsymUpload'],
  },
  {
    key: 'remote',
    label: 'Remote',
    types: ['remoteSsh'],
  },
  {
    key: 'iosBuild',
    label: 'iOS — Build',
    types: ['xcodeSelect', 'xcodebuild', 'xcodebuildAnalyze', 'buildAppGym', 'swiftPackageResolve', 'cocoapodsInstall'],
  },
  {
    key: 'iosSigning',
    label: 'iOS — Signing',
    types: [
      'keychainUnlock',
      'provisioningProfileInstall',
      'sigh',
      'fastlaneMatch',
      'resign',
      'pushCertificate',
      'certManage',
      'registerDevices',
    ],
  },
  {
    key: 'iosDistribute',
    label: 'iOS — Distribute & ASC',
    types: [
      'notarize',
      'stapleNotarization',
      'testflightUpload',
      'testflightSetWhatToTest',
      'testflightPublicLink',
      'testflightManage',
      'appStorePrecheck',
      'appStoreCreate',
      'appStoreUpload',
      'appStoreConnectApi',
    ],
  },
  {
    key: 'iosVersioning',
    label: 'iOS — Versioning & Plist',
    types: ['incrementBuildNumber', 'getBuildNumber', 'updateInfoPlist', 'xcresultParse'],
  },
  {
    key: 'iosQuality',
    label: 'iOS — Quality',
    types: ['swiftlint', 'swiftFormat', 'peripheryScan', 'slatherCoverage', 'xcovGate'],
  },
  {
    key: 'iosScreenshots',
    label: 'iOS — Screenshots',
    types: ['snapshot', 'frameit'],
  },
  {
    key: 'android',
    label: 'Android',
    types: ['gradleBuild', 'adbConnect', 'adbInstall', 'adbShellLaunch', 'adbLogcat'],
  },
];

// Build-time guard: every StepType must be assigned to exactly one category.
// Throws at module load if a step is missing or duplicated, so palette UI
// never silently hides a node type.
{
  const seen = new Set<StepType>();
  for (const group of STEP_CATEGORIES) {
    for (const t of group.types) {
      if (seen.has(t)) {
        throw new Error(`STEP_CATEGORIES: step "${t}" appears in more than one group`);
      }
      seen.add(t);
    }
  }
  const missing = STEP_TYPES.filter((t) => !seen.has(t));
  if (missing.length > 0) {
    throw new Error(`STEP_CATEGORIES: missing groups for: ${missing.join(', ')}`);
  }
}
