import type { StepType } from '@buildpilot/shared-types';

export interface StepFieldSchema {
  name: string;
  label: string;
  // 'branchSelect'  = project-aware combobox populated with the project's
  //                   local + remote branches.
  // 'hostSelect'    = combobox listing entries from ~/.buildpilot/hosts.json
  //                   plus an "(inline)" option that hands control back to
  //                   the host/identityFile/password fields below it.
  // The host UI supplies both lists.
  type: 'text' | 'textarea' | 'select' | 'number' | 'branchSelect' | 'hostSelect';
  options?: readonly string[];
  required?: boolean;
  placeholder?: string;
  help?: string;
  defaultValue?: string | number;
}

export interface StepDefinition {
  type: StepType;
  label: string;
  description: string;
  color: string; // background colour for the React Flow node
  icon: string;  // lucide-react icon name
  fields: readonly StepFieldSchema[];
}

const UNITY_BUILD_TARGETS = [
  'StandaloneLinux64',
  'StandaloneWindows64',
  'StandaloneOSX',
  'iOS',
  'Android',
  'WebGL',
] as const;

export const STEP_DEFINITIONS: Record<StepType, StepDefinition> = {
  checkout: {
    type: 'checkout',
    label: 'Checkout',
    description: 'Switch the project working tree to a specific branch.',
    color: '#0ea5e9',
    icon: 'GitBranch',
    fields: [
      { name: 'branch', label: 'Branch', type: 'branchSelect', required: true },
    ],
  },
  pull: {
    type: 'pull',
    label: 'Pull',
    description: 'Fetch and fast-forward the current branch from the remote.',
    color: '#10b981',
    icon: 'ArrowDownToLine',
    fields: [
      { name: 'remote', label: 'Remote', type: 'text', placeholder: 'origin' },
    ],
  },
  gitMerge: {
    type: 'gitMerge',
    label: 'Git Merge',
    description: 'Merge another branch into the current one (compose with AI auto-fix to resolve conflicts).',
    color: '#14b8a6',
    icon: 'GitMerge',
    fields: [
      { name: 'sourceBranch', label: 'Source branch', type: 'branchSelect', required: true },
      {
        name: 'noFastForward',
        label: 'Always create a merge commit (--no-ff)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'message',
        label: 'Commit message (optional)',
        type: 'text',
        placeholder: 'Merge {{source}} into {{current}}',
      },
    ],
  },
  shell: {
    type: 'shell',
    label: 'Shell',
    description: 'Run an arbitrary shell command inside the project directory.',
    color: '#f59e0b',
    icon: 'Terminal',
    fields: [
      {
        name: 'command',
        label: 'Command',
        type: 'textarea',
        required: true,
        placeholder: 'pnpm install && pnpm test',
      },
      {
        name: 'cwd',
        label: 'Working dir (relative)',
        type: 'text',
        placeholder: '. (defaults to project root)',
      },
    ],
  },
  unityBatch: {
    type: 'unityBatch',
    label: 'Unity Batch Build',
    description: 'Run Unity in batch mode and invoke a static build method.',
    color: '#a855f7',
    icon: 'Gamepad2',
    fields: [
      {
        name: 'unityPath',
        label: 'Unity executable path',
        type: 'text',
        required: true,
        placeholder: 'C:/Program Files/Unity/Hub/Editor/<version>/Editor/Unity.exe',
      },
      {
        name: 'buildTarget',
        label: 'Build target',
        type: 'select',
        required: true,
        options: UNITY_BUILD_TARGETS,
      },
      {
        name: 'executeMethod',
        label: 'Static method',
        type: 'text',
        required: true,
        placeholder: 'BuildScript.BuildDedicatedServer',
      },
      {
        name: 'extraArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: '-customArg value',
      },
      {
        name: 'logPath',
        label: 'Log file path',
        type: 'text',
        placeholder: '(optional — otherwise streamed to stdout)',
      },
    ],
  },
  httpRequest: {
    type: 'httpRequest',
    label: 'HTTP Request',
    description: 'Make an HTTP call and fail the step on a non-success status.',
    color: '#06b6d4',
    icon: 'Globe',
    fields: [
      {
        name: 'method',
        label: 'Method',
        type: 'select',
        required: true,
        options: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] as const,
        defaultValue: 'POST',
      },
      {
        name: 'url',
        label: 'URL',
        type: 'text',
        required: true,
        placeholder: 'https://api.example.com/build-finished',
      },
      {
        name: 'headers',
        label: 'Headers (one per line, "Key: Value")',
        type: 'textarea',
        placeholder: 'Authorization: Bearer ${env.TOKEN}\nContent-Type: application/json',
      },
      {
        name: 'body',
        label: 'Body',
        type: 'textarea',
        placeholder: '{"status":"green"}',
      },
      {
        name: 'expectedStatus',
        label: 'Expected status (comma-separated)',
        type: 'text',
        placeholder: '200,201,204 (defaults to 2xx)',
      },
    ],
  },
  slackNotify: {
    type: 'slackNotify',
    label: 'Slack Notify',
    description: 'Post a message to a Slack incoming webhook.',
    color: '#22d3ee',
    icon: 'MessageSquare',
    fields: [
      {
        name: 'webhookUrl',
        label: 'Webhook URL',
        type: 'text',
        required: true,
        placeholder: 'https://hooks.slack.com/services/T.../B.../...',
      },
      {
        name: 'text',
        label: 'Message',
        type: 'textarea',
        required: true,
        placeholder: ':white_check_mark: Build finished',
      },
    ],
  },
  discordNotify: {
    type: 'discordNotify',
    label: 'Discord Notify',
    description: 'Post a message to a Discord webhook.',
    color: '#8b5cf6',
    icon: 'MessageCircle',
    fields: [
      {
        name: 'webhookUrl',
        label: 'Webhook URL',
        type: 'text',
        required: true,
        placeholder: 'https://discord.com/api/webhooks/.../...',
      },
      {
        name: 'content',
        label: 'Message',
        type: 'textarea',
        required: true,
        placeholder: '✅ Build finished',
      },
    ],
  },
  telegramNotify: {
    type: 'telegramNotify',
    label: 'Telegram Notify',
    description: 'Send a message via Telegram Bot API (token + chat fall back to ~/.buildpilot/config.json).',
    color: '#38bdf8',
    icon: 'Send',
    fields: [
      {
        name: 'botToken',
        label: 'Bot token (leave blank for default)',
        type: 'text',
        placeholder: '123456:ABC-DEF…',
      },
      {
        name: 'chatId',
        label: 'Chat id (leave blank for default)',
        type: 'text',
        placeholder: '@yourchannel or 12345678',
      },
      {
        name: 'text',
        label: 'Message',
        type: 'textarea',
        required: true,
        placeholder: '✅ NetworkTest server build finished\n<i>commit</i> <code>{{sha}}</code>',
      },
      {
        name: 'parseMode',
        label: 'Parse mode',
        type: 'select',
        options: ['plain', 'HTML', 'MarkdownV2'] as const,
        defaultValue: 'plain',
      },
      {
        name: 'silent',
        label: 'Send silently (no sound)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
    ],
  },
  remoteSsh: {
    type: 'remoteSsh',
    label: 'Remote SSH',
    description: 'Run a shell command on a remote host via ssh — the foundation for cross-OS builds.',
    color: '#64748b',
    icon: 'Server',
    fields: [
      {
        name: 'hostId',
        label: 'Saved host (or pick "(inline)" to type one below)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Host (used when no saved host is picked)',
        type: 'text',
        placeholder: 'user@mac-builder.local',
        help: 'Optionally include a port: user@host:2222',
      },
      {
        name: 'identityFile',
        label: 'Identity file (use this OR password)',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'Password (plaintext — see secrets warning)',
        type: 'text',
        placeholder: '(leave blank to use identityFile)',
      },
      {
        name: 'cwd',
        label: 'Remote working dir',
        type: 'text',
        placeholder: '/Users/build/projects/MyGame',
      },
      {
        name: 'command',
        label: 'Command',
        type: 'textarea',
        required: true,
        placeholder: 'git pull && xcodebuild -scheme MyGame -configuration Release archive',
      },
      {
        name: 'skipStrictHostKey',
        label: 'Skip strict host key checking',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
    ],
  },
  sftpUpload: {
    type: 'sftpUpload',
    label: 'SFTP Upload',
    description: 'Upload a single file over SSH/SFTP (key or password auth).',
    color: '#475569',
    icon: 'Upload',
    fields: [
      {
        name: 'hostId',
        label: 'Saved host (or pick "(inline)" to type one below)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Host (used when no saved host is picked)',
        type: 'text',
        placeholder: 'root@game-server.example:22',
      },
      {
        name: 'identityFile',
        label: 'Identity file (use this OR password)',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'Password (plaintext — see secrets warning)',
        type: 'text',
        placeholder: '(leave blank to use identityFile)',
      },
      {
        name: 'localPath',
        label: 'Local file (relative to project, or absolute)',
        type: 'text',
        required: true,
        placeholder: 'Builds/Server.rar',
      },
      {
        name: 'remotePath',
        label: 'Remote destination (absolute path)',
        type: 'text',
        required: true,
        placeholder: '/home/Game/Server.rar',
      },
      {
        name: 'skipStrictHostKey',
        label: 'Skip strict host key checking',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
    ],
  },
  s3Upload: {
    type: 's3Upload',
    label: 'S3 Upload',
    description: 'Upload a file to AWS S3 with optional presigned URL + manifest. Stores credentials in plaintext.',
    color: '#fb923c',
    icon: 'CloudUpload',
    fields: [
      {
        name: 'accessKeyId',
        label: 'AWS Access Key ID (plaintext — secrets vault TBD)',
        type: 'text',
        required: true,
        placeholder: 'AKIA…',
      },
      {
        name: 'secretAccessKey',
        label: 'AWS Secret Access Key',
        type: 'text',
        required: true,
        placeholder: '40-char secret',
      },
      {
        name: 'region',
        label: 'Region',
        type: 'text',
        required: true,
        placeholder: 'eu-central-1',
      },
      {
        name: 'bucket',
        label: 'Bucket',
        type: 'text',
        required: true,
        placeholder: 'my-build-bucket',
      },
      {
        name: 'localPath',
        label: 'Local file',
        type: 'text',
        required: true,
        placeholder: 'Builds/Server.rar',
      },
      {
        name: 'key',
        label: 'S3 object key (path inside bucket)',
        type: 'text',
        required: true,
        placeholder: 'linux-x86_64/Server.rar',
      },
      {
        name: 'storageClass',
        label: 'Storage class',
        type: 'select',
        options: [
          'STANDARD',
          'STANDARD_IA',
          'REDUCED_REDUNDANCY',
          'GLACIER',
          'DEEP_ARCHIVE',
        ] as const,
        defaultValue: 'STANDARD',
      },
      {
        name: 'makePresignedUrl',
        label: 'Generate presigned URL',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'presignedExpiresSec',
        label: 'Presigned URL expiry (seconds)',
        type: 'number',
        placeholder: '604800 = 7 days',
      },
      {
        name: 'manifestKey',
        label: 'Manifest object key (optional, e.g. stable.json)',
        type: 'text',
        placeholder: 'stable.json',
      },
      {
        name: 'manifestChannel',
        label: 'Manifest channel',
        type: 'text',
        placeholder: 'stable',
      },
      {
        name: 'manifestPlatform',
        label: 'Manifest platform',
        type: 'text',
        placeholder: 'linux-x86_64',
      },
    ],
  },
  xcodebuild: {
    type: 'xcodebuild',
    label: 'xcodebuild',
    description: 'Drive xcodebuild for iOS / macOS builds. Local or via a saved Mac host.',
    color: '#0891b2',
    icon: 'Apple',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host (used when no saved host is picked)',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'workspacePath',
        label: 'Workspace (.xcworkspace, optional)',
        type: 'text',
        placeholder: 'MyGame.xcworkspace',
      },
      {
        name: 'projectPath',
        label: 'Project (.xcodeproj, used if no workspace)',
        type: 'text',
        placeholder: 'MyGame.xcodeproj',
      },
      {
        name: 'scheme',
        label: 'Scheme (required for build / archive / test / clean)',
        type: 'text',
        placeholder: 'MyGame',
      },
      {
        name: 'configuration',
        label: 'Configuration',
        type: 'select',
        options: ['Debug', 'Release'] as const,
        defaultValue: 'Release',
      },
      {
        name: 'buildAction',
        label: 'Action',
        type: 'select',
        options: ['build', 'archive', 'test', 'clean', 'exportArchive'] as const,
        defaultValue: 'archive',
      },
      {
        name: 'destination',
        label: 'Destination',
        type: 'text',
        placeholder: 'generic/platform=iOS',
      },
      {
        name: 'archivePath',
        label: 'Archive path (archive: output, exportArchive: input)',
        type: 'text',
        placeholder: 'build/MyGame.xcarchive',
      },
      {
        name: 'exportPath',
        label: 'Export output dir (exportArchive only)',
        type: 'text',
        placeholder: 'build/export',
      },
      {
        name: 'exportOptionsPlist',
        label: 'ExportOptions.plist path (exportArchive only)',
        type: 'text',
        placeholder: 'signing/ExportOptions.plist',
      },
      {
        name: 'additionalArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: 'CODE_SIGNING_ALLOWED=NO',
      },
    ],
  },
  testflightUpload: {
    type: 'testflightUpload',
    label: 'TestFlight Upload',
    description: 'Upload an .ipa to App Store Connect / TestFlight via xcrun altool.',
    color: '#0ea5e9',
    icon: 'PlaneTakeoff',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host (used when no saved host is picked)',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'ipaPath',
        label: '.ipa path',
        type: 'text',
        required: true,
        placeholder: 'build/MyGame.ipa',
      },
      {
        name: 'platform',
        label: 'Platform',
        type: 'select',
        options: ['ios', 'macos', 'tvos'] as const,
        defaultValue: 'ios',
      },
      {
        name: 'authMethod',
        label: 'Auth method',
        type: 'select',
        options: ['apiKey', 'appleId'] as const,
        defaultValue: 'apiKey',
      },
      {
        name: 'apiKeyId',
        label: 'API Key ID (apiKey auth)',
        type: 'text',
        placeholder: 'ABC123XYZ',
        help: 'Place AuthKey_<id>.p8 at ~/.appstoreconnect/private_keys/ on the host.',
      },
      {
        name: 'apiIssuerId',
        label: 'API Issuer ID (apiKey auth)',
        type: 'text',
        placeholder: '57246542-96fe-1a63-e053-0824d011072a',
      },
      {
        name: 'appleId',
        label: 'Apple ID (appleId auth)',
        type: 'text',
        placeholder: 'developer@example.com',
      },
      {
        name: 'appPassword',
        label: 'App-specific password (appleId auth — plaintext)',
        type: 'text',
        placeholder: 'xxxx-xxxx-xxxx-xxxx',
      },
      {
        name: 'additionalArgs',
        label: 'Extra altool args',
        type: 'text',
        placeholder: '--verbose',
      },
    ],
  },
  keychainUnlock: {
    type: 'keychainUnlock',
    label: 'Keychain Unlock',
    description: 'Unlock a macOS keychain so codesign / xcodebuild don’t prompt.',
    color: '#f97316',
    icon: 'KeyRound',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'Keychain password (plaintext)',
        type: 'text',
        required: true,
        placeholder: '(matches the user login password by default)',
      },
      {
        name: 'keychain',
        label: 'Keychain path',
        type: 'text',
        placeholder: 'login.keychain-db (default)',
      },
      {
        name: 'unlockTimeoutSec',
        label: 'Re-lock after (seconds, optional)',
        type: 'number',
        placeholder: '3600',
      },
    ],
  },
  provisioningProfileInstall: {
    type: 'provisioningProfileInstall',
    label: 'Install Provisioning Profile',
    description:
      'Drop a .mobileprovision into ~/Library/MobileDevice/Provisioning Profiles (locally or remote).',
    color: '#a3e635',
    icon: 'BadgeCheck',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'profilePath',
        label: '.mobileprovision file (local — uploaded automatically when remote)',
        type: 'text',
        required: true,
        placeholder: 'signing/MyGame_AdHoc.mobileprovision',
      },
    ],
  },
  notarize: {
    type: 'notarize',
    label: 'Notarize',
    description:
      'Submit a .app/.dmg/.pkg/.zip to Apple notary service via xcrun notarytool. Required for macOS distribution outside the App Store.',
    color: '#f43f5e',
    icon: 'ShieldCheck',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'bundlePath',
        label: 'Bundle to notarize (.app, .dmg, .pkg, .zip)',
        type: 'text',
        required: true,
        placeholder: 'build/MyApp.dmg',
      },
      {
        name: 'authMethod',
        label: 'Auth method',
        type: 'select',
        options: ['apiKey', 'appleId'] as const,
        defaultValue: 'apiKey',
      },
      {
        name: 'apiKeyPath',
        label: 'AuthKey .p8 path (apiKey auth)',
        type: 'text',
        placeholder: '~/.appstoreconnect/private_keys/AuthKey_ABC123.p8',
      },
      {
        name: 'apiKeyId',
        label: 'API Key ID (apiKey auth)',
        type: 'text',
        placeholder: 'ABC123XYZ',
      },
      {
        name: 'apiIssuerId',
        label: 'API Issuer ID (apiKey auth)',
        type: 'text',
        placeholder: '57246542-…',
      },
      {
        name: 'appleId',
        label: 'Apple ID (appleId auth)',
        type: 'text',
        placeholder: 'developer@example.com',
      },
      {
        name: 'appPassword',
        label: 'App-specific password (appleId auth — plaintext)',
        type: 'text',
        placeholder: 'xxxx-xxxx-xxxx-xxxx',
      },
      {
        name: 'teamId',
        label: 'Team ID (appleId auth)',
        type: 'text',
        placeholder: 'AB12CDE34F',
      },
      {
        name: 'wait',
        label: 'Wait for Apple verdict before continuing',
        type: 'select',
        options: ['true', 'false'] as const,
        defaultValue: 'true',
      },
      {
        name: 'additionalArgs',
        label: 'Extra notarytool args',
        type: 'text',
        placeholder: '--verbose',
      },
    ],
  },
  dsymUpload: {
    type: 'dsymUpload',
    label: 'Upload dSYMs',
    description: 'Send debug symbols to a crash reporting service so stack traces resolve in production.',
    color: '#6366f1',
    icon: 'Bug',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'backend',
        label: 'Crash reporting backend',
        type: 'select',
        required: true,
        options: ['crashlytics', 'sentry', 'bugsnag'] as const,
        defaultValue: 'sentry',
      },
      {
        name: 'dsymPath',
        label: 'dSYM / .xcarchive / dSYM dir',
        type: 'text',
        required: true,
        placeholder: 'build/MyGame.xcarchive',
      },
      {
        name: 'googleServicePlistPath',
        label: 'GoogleService-Info.plist (Crashlytics only)',
        type: 'text',
        placeholder: 'GoogleService-Info.plist',
      },
      {
        name: 'uploadSymbolsBinary',
        label: 'Crashlytics upload-symbols path (optional)',
        type: 'text',
        placeholder: '(uses upload-symbols on PATH by default)',
      },
      {
        name: 'platform',
        label: 'Platform (Crashlytics only)',
        type: 'select',
        options: ['ios', 'macos', 'tvos', 'watchos'] as const,
        defaultValue: 'ios',
      },
      {
        name: 'sentryOrg',
        label: 'Sentry org (Sentry only)',
        type: 'text',
        placeholder: 'my-team',
      },
      {
        name: 'sentryProject',
        label: 'Sentry project (Sentry only)',
        type: 'text',
        placeholder: 'mygame-ios',
      },
      {
        name: 'sentryAuthToken',
        label: 'Sentry auth token (plaintext — passed via SENTRY_AUTH_TOKEN env)',
        type: 'text',
        placeholder: '…',
      },
      {
        name: 'bugsnagApiKey',
        label: 'Bugsnag API key (Bugsnag only)',
        type: 'text',
        placeholder: '32-char hex',
      },
      {
        name: 'bugsnagCliPath',
        label: 'bugsnag-cli path (optional)',
        type: 'text',
        placeholder: '(uses bugsnag-cli on PATH by default)',
      },
      {
        name: 'additionalArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: '--verbose',
      },
    ],
  },
  xcresultParse: {
    type: 'xcresultParse',
    label: 'Parse xcresult',
    description: 'Run xcresulttool against a .xcresult bundle and emit a "X/Y tests passed" summary.',
    color: '#84cc16',
    icon: 'ListChecks',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'bundlePath',
        label: 'Path to .xcresult bundle',
        type: 'text',
        required: true,
        placeholder: 'build/test-results.xcresult',
      },
      {
        name: 'failOnTestFailure',
        label: 'Fail step when any test failed',
        type: 'select',
        options: ['true', 'false'] as const,
        defaultValue: 'true',
      },
    ],
  },
  cocoapodsInstall: {
    type: 'cocoapodsInstall',
    label: 'CocoaPods Install',
    description: 'Run `pod install` (or `pod update`) to fetch CocoaPods dependencies.',
    color: '#ef4444',
    icon: 'Box',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'command',
        label: 'Command',
        type: 'select',
        options: ['install', 'update'] as const,
        defaultValue: 'install',
      },
      {
        name: 'repoUpdate',
        label: 'Pass --repo-update (slower, ensures fresh specs)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'useBundleExec',
        label: 'Prefix with `bundle exec`',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'cwd',
        label: 'Working dir (where Podfile lives)',
        type: 'text',
        placeholder: '. (defaults to project root)',
      },
      {
        name: 'additionalArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: '--verbose',
      },
    ],
  },
  swiftPackageResolve: {
    type: 'swiftPackageResolve',
    label: 'SPM Resolve',
    description: 'Pre-resolve Swift Package Manager dependencies via xcodebuild -resolvePackageDependencies.',
    color: '#fb923c',
    icon: 'Boxes',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'workspacePath',
        label: 'Workspace (.xcworkspace)',
        type: 'text',
        placeholder: 'MyGame.xcworkspace',
      },
      {
        name: 'projectPath',
        label: 'Project (.xcodeproj, used if no workspace)',
        type: 'text',
        placeholder: 'MyGame.xcodeproj',
      },
      {
        name: 'scheme',
        label: 'Scheme (optional — narrows resolution to one scheme)',
        type: 'text',
        placeholder: 'MyGame',
      },
      {
        name: 'clonedSourcePackagesDirPath',
        label: 'SourcePackages cache dir (optional)',
        type: 'text',
        placeholder: 'build/SourcePackages',
      },
      {
        name: 'additionalArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: '-quiet',
      },
    ],
  },
  fastlaneMatch: {
    type: 'fastlaneMatch',
    label: 'Fastlane Match',
    description:
      'Sync code-signing certs + provisioning profiles via fastlane match. Pair with keychainUnlock so the certs land in an unlocked keychain.',
    color: '#22c55e',
    icon: 'Wrench',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password (only for inline host)',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'matchType',
        label: 'Type',
        type: 'select',
        required: true,
        options: ['development', 'adhoc', 'appstore', 'enterprise', 'developer_id'] as const,
        defaultValue: 'appstore',
      },
      {
        name: 'appIdentifier',
        label: 'App identifier (comma-separated for multiple)',
        type: 'text',
        placeholder: 'com.example.MyGame',
      },
      {
        name: 'gitUrl',
        label: 'Match Git URL (or leave blank to use Matchfile)',
        type: 'text',
        placeholder: 'https://github.com/example/match-secrets.git',
      },
      {
        name: 'gitBranch',
        label: 'Match Git branch',
        type: 'text',
        placeholder: 'main',
      },
      {
        name: 'password',
        label: 'MATCH_PASSWORD (encrypts the match repo — plaintext)',
        type: 'text',
        placeholder: '…',
      },
      {
        name: 'keychainName',
        label: 'Target keychain (empty = login.keychain-db)',
        type: 'text',
        placeholder: 'login.keychain-db',
      },
      {
        name: 'keychainPassword',
        label: 'Keychain password (plaintext)',
        type: 'text',
        placeholder: '(only if keychain is locked)',
      },
      {
        name: 'readonly',
        label: 'Readonly mode (recommended for CI)',
        type: 'select',
        options: ['true', 'false'] as const,
        defaultValue: 'true',
      },
      {
        name: 'cwd',
        label: 'Working dir on the runner (where Matchfile lives)',
        type: 'text',
        placeholder: '. (defaults to project root on local runs)',
      },
      {
        name: 'additionalArgs',
        label: 'Extra fastlane args',
        type: 'text',
        placeholder: '--verbose',
      },
    ],
  },
  stapleNotarization: {
    type: 'stapleNotarization',
    label: 'Staple Notarization',
    description:
      'Embed the notarization ticket into a notarized bundle so Gatekeeper can verify it offline.',
    color: '#fb7185',
    icon: 'Stamp',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'bundlePath',
        label: 'Bundle that already passed notarization',
        type: 'text',
        required: true,
        placeholder: 'build/MyApp.dmg',
      },
    ],
  },
  artifact: {
    type: 'artifact',
    label: 'Artifact',
    description: 'Record build outputs (paths or globs) so they can be downloaded later.',
    color: '#facc15',
    icon: 'Package',
    fields: [
      {
        name: 'paths',
        label: 'Paths (one per line)',
        type: 'textarea',
        required: true,
        placeholder:
          'Builds/Linux/server.x86_64\nBuilds/Linux/server_Data/**\nartifacts/dist/**',
        help: 'A path can be a file, a directory (one level), or end with /** for recursive walk.',
      },
    ],
  },
  xcodeSelect: {
    type: 'xcodeSelect',
    label: 'Xcode Select',
    description: 'Switch the active Xcode toolchain via `xcode-select -s`. Local or via a saved Mac host.',
    color: '#38bdf8',
    icon: 'Wand2',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'xcodePath',
        label: 'Xcode .app bundle path',
        type: 'text',
        required: true,
        placeholder: '/Applications/Xcode_15.4.app',
        help: 'Passed to `sudo xcode-select -s`. The user must have passwordless sudo for xcode-select on the target host.',
      },
    ],
  },
  ensureGitStatusClean: {
    type: 'ensureGitStatusClean',
    label: 'Ensure Clean Tree',
    description: 'Pre-flight gate: fail the pipeline if `git status --porcelain` reports any modified or untracked paths.',
    color: '#f59e0b',
    icon: 'ShieldAlert',
    fields: [
      {
        name: 'hostId',
        label: 'Saved host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '. (defaults to project root)',
      },
    ],
  },
  incrementBuildNumber: {
    type: 'incrementBuildNumber',
    label: 'Increment Build #',
    description:
      'Bump CFBundleVersion via `agvtool` (auto-increment by 1 or set explicitly) or `PlistBuddy`.',
    color: '#22c55e',
    icon: 'Plus',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'mode',
        label: 'Mode',
        type: 'select',
        options: ['agvtool', 'plistBuddy'] as const,
        defaultValue: 'agvtool',
      },
      {
        name: 'versionString',
        label: 'Version (blank = agvtool next-version auto-bump)',
        type: 'text',
        placeholder: '42',
        help: 'Blank with mode=agvtool runs `next-version -all`. Required for plistBuddy.',
      },
      {
        name: 'plistPath',
        label: 'Info.plist path (plistBuddy only)',
        type: 'text',
        placeholder: 'MyApp/Info.plist',
      },
      {
        name: 'cwd',
        label: 'Working dir (must contain .xcodeproj for agvtool)',
        type: 'text',
        placeholder: '. (defaults to project root)',
      },
    ],
  },
  getBuildNumber: {
    type: 'getBuildNumber',
    label: 'Get Build #',
    description:
      'Read CFBundleVersion via `agvtool what-version -terse` or `PlistBuddy Print :CFBundleVersion`.',
    color: '#10b981',
    icon: 'Hash',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'build@mac-builder.local',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'mode',
        label: 'Mode',
        type: 'select',
        options: ['agvtool', 'plistBuddy'] as const,
        defaultValue: 'agvtool',
      },
      {
        name: 'plistPath',
        label: 'Info.plist path (plistBuddy only)',
        type: 'text',
        placeholder: 'MyApp/Info.plist',
      },
      {
        name: 'cwd',
        label: 'Working dir (must contain .xcodeproj for agvtool)',
        type: 'text',
        placeholder: '. (defaults to project root)',
      },
    ],
  },
  changelogFromGitCommits: {
    type: 'changelogFromGitCommits',
    label: 'Changelog From Git',
    description:
      'Generate release-note text from a commit range via `git log --pretty`. Feeds testflight whatToTest / App Store deliver release notes.',
    color: '#a855f7',
    icon: 'ScrollText',
    fields: [
      {
        name: 'hostId',
        label: 'Saved host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'user@host',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'fromRef',
        label: 'From ref (exclusive)',
        type: 'text',
        required: true,
        placeholder: 'v1.4.0',
      },
      {
        name: 'toRef',
        label: 'To ref (inclusive, default HEAD)',
        type: 'text',
        placeholder: 'HEAD',
      },
      {
        name: 'format',
        label: 'Format',
        type: 'select',
        options: ['subject', 'subject-body', 'oneline'] as const,
        defaultValue: 'subject',
      },
      {
        name: 'maxCommits',
        label: 'Max commits to include',
        type: 'number',
        placeholder: '1000',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '.',
      },
    ],
  },
  updateInfoPlist: {
    type: 'updateInfoPlist',
    label: 'Update Info.plist',
    description:
      'Set / Add / Delete a key in any plist via `/usr/libexec/PlistBuddy`. Common pre-build mutation for bundle id, version, endpoint URLs.',
    color: '#f59e0b',
    icon: 'FileCog',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'user@host',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'plistPath',
        label: 'Plist path',
        type: 'text',
        required: true,
        placeholder: 'MyApp/Info.plist',
      },
      {
        name: 'key',
        label: 'Key path (e.g. :CFBundleDisplayName)',
        type: 'text',
        required: true,
        placeholder: ':CFBundleDisplayName',
      },
      {
        name: 'operation',
        label: 'Operation',
        type: 'select',
        options: ['set', 'add-string', 'delete'] as const,
        defaultValue: 'set',
      },
      {
        name: 'value',
        label: 'Value (required for set / add-string)',
        type: 'text',
        placeholder: 'new value',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '.',
      },
    ],
  },
  swiftlint: {
    type: 'swiftlint',
    label: 'SwiftLint',
    description: 'Run swiftlint lint / fix / analyze with optional config + reporter selection.',
    color: '#10b981',
    icon: 'CodeXml',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'user@host',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'mode',
        label: 'Mode',
        type: 'select',
        options: ['lint', 'fix', 'analyze'] as const,
        defaultValue: 'lint',
      },
      {
        name: 'configFile',
        label: 'Config file path (.swiftlint.yml, optional)',
        type: 'text',
        placeholder: '.swiftlint.yml',
      },
      {
        name: 'paths',
        label: 'Paths (one per line, optional)',
        type: 'textarea',
        placeholder: 'Sources\nTests',
      },
      {
        name: 'strict',
        label: 'Treat warnings as errors (--strict)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'reporter',
        label: 'Reporter',
        type: 'select',
        options: ['xcode', 'json', 'junit', 'markdown', 'html', 'emoji'] as const,
        defaultValue: 'xcode',
      },
      {
        name: 'quiet',
        label: 'Quiet (suppress per-rule progress)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '.',
      },
    ],
  },
  swiftFormat: {
    type: 'swiftFormat',
    label: 'swift-format',
    description: 'Apple swift-format lint or in-place format with optional configuration.',
    color: '#0ea5e9',
    icon: 'AlignLeft',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'user@host',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'mode',
        label: 'Mode',
        type: 'select',
        options: ['lint', 'format'] as const,
        defaultValue: 'lint',
      },
      {
        name: 'configFile',
        label: 'Config file path (.swift-format, optional)',
        type: 'text',
        placeholder: '.swift-format',
      },
      {
        name: 'paths',
        label: 'Paths (one per line)',
        type: 'textarea',
        placeholder: 'Sources',
      },
      {
        name: 'recursive',
        label: 'Recursive (--recursive)',
        type: 'select',
        options: ['true', 'false'] as const,
        defaultValue: 'true',
      },
      {
        name: 'parallel',
        label: 'Parallel (--parallel)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '.',
      },
    ],
  },
  xcodebuildAnalyze: {
    type: 'xcodebuildAnalyze',
    label: 'xcodebuild Analyze',
    description: 'Run Apple Clang static analyzer via `xcrun xcodebuild analyze`.',
    color: '#0891b2',
    icon: 'Microscope',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'user@host',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'workspacePath',
        label: 'Workspace (.xcworkspace)',
        type: 'text',
        placeholder: 'MyApp.xcworkspace',
      },
      {
        name: 'projectPath',
        label: 'Project (.xcodeproj, used if no workspace)',
        type: 'text',
        placeholder: 'MyApp.xcodeproj',
      },
      {
        name: 'scheme',
        label: 'Scheme',
        type: 'text',
        required: true,
        placeholder: 'MyApp',
      },
      {
        name: 'configuration',
        label: 'Configuration',
        type: 'select',
        options: ['Debug', 'Release'] as const,
        defaultValue: 'Release',
      },
      {
        name: 'destination',
        label: 'Destination',
        type: 'text',
        placeholder: 'generic/platform=iOS',
      },
      {
        name: 'additionalArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: 'CODE_SIGNING_ALLOWED=NO',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '.',
      },
    ],
  },
  peripheryScan: {
    type: 'peripheryScan',
    label: 'Periphery Scan',
    description: 'Detect dead Swift code via `periphery scan`. Pair with strict mode to fail builds.',
    color: '#a855f7',
    icon: 'Search',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'user@host',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'workspacePath',
        label: 'Workspace (.xcworkspace)',
        type: 'text',
        placeholder: 'MyApp.xcworkspace',
      },
      {
        name: 'projectPath',
        label: 'Project (.xcodeproj, used if no workspace)',
        type: 'text',
        placeholder: 'MyApp.xcodeproj',
      },
      {
        name: 'schemes',
        label: 'Schemes (comma-separated)',
        type: 'text',
        placeholder: 'Free,Pro',
      },
      {
        name: 'targets',
        label: 'Targets (comma-separated)',
        type: 'text',
        placeholder: 'AppCore,AppUI',
      },
      {
        name: 'format',
        label: 'Output format',
        type: 'select',
        options: ['xcode', 'json', 'csv', 'github-actions', 'checkstyle'] as const,
        defaultValue: 'xcode',
      },
      {
        name: 'strict',
        label: 'Strict (treat unused as build errors)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'configFile',
        label: 'Config file (.periphery.yml, optional)',
        type: 'text',
        placeholder: '.periphery.yml',
      },
      {
        name: 'additionalArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: '--clean-build',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '.',
      },
    ],
  },
  slatherCoverage: {
    type: 'slatherCoverage',
    label: 'Slather Coverage',
    description: 'Generate coverage reports from .xcresult via the slather gem (HTML / JSON / Cobertura / Sonar / simple).',
    color: '#84cc16',
    icon: 'Percent',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'user@host',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'projectPath',
        label: 'Project (.xcodeproj)',
        type: 'text',
        required: true,
        placeholder: 'MyApp.xcodeproj',
      },
      {
        name: 'workspacePath',
        label: 'Workspace (.xcworkspace, optional)',
        type: 'text',
        placeholder: 'MyApp.xcworkspace',
      },
      {
        name: 'scheme',
        label: 'Scheme',
        type: 'text',
        placeholder: 'MyApp',
      },
      {
        name: 'format',
        label: 'Output format',
        type: 'select',
        options: ['html', 'json', 'cobertura', 'simple', 'sonarqube'] as const,
        defaultValue: 'html',
      },
      {
        name: 'outputDirectory',
        label: 'Output directory',
        type: 'text',
        placeholder: 'coverage_html',
      },
      {
        name: 'buildDirectory',
        label: 'Build directory (DerivedData)',
        type: 'text',
        placeholder: 'build',
      },
      {
        name: 'additionalArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: '--ignore */Pods/*',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '.',
      },
    ],
  },
  xcovGate: {
    type: 'xcovGate',
    label: 'xcov Coverage Gate',
    description: 'Parse xcov coverage and fail the build below a minimum percentage.',
    color: '#facc15',
    icon: 'Gauge',
    fields: [
      {
        name: 'hostId',
        label: 'Saved Mac host (or pick "(inline)" / leave blank for local)',
        type: 'hostSelect',
      },
      {
        name: 'host',
        label: 'Inline host',
        type: 'text',
        placeholder: 'user@host',
      },
      {
        name: 'identityFile',
        label: 'Identity file',
        type: 'text',
        placeholder: '~/.ssh/id_ed25519',
      },
      {
        name: 'password',
        label: 'SSH password',
        type: 'text',
        placeholder: '(use this OR identityFile)',
      },
      {
        name: 'workspacePath',
        label: 'Workspace (.xcworkspace)',
        type: 'text',
        placeholder: 'MyApp.xcworkspace',
      },
      {
        name: 'projectPath',
        label: 'Project (.xcodeproj, used if no workspace)',
        type: 'text',
        placeholder: 'MyApp.xcodeproj',
      },
      {
        name: 'scheme',
        label: 'Scheme',
        type: 'text',
        required: true,
        placeholder: 'MyApp',
      },
      {
        name: 'minimumCoveragePercentage',
        label: 'Minimum coverage percentage (0 = no gate)',
        type: 'number',
        defaultValue: 0,
      },
      {
        name: 'outputDirectory',
        label: 'Output directory',
        type: 'text',
        placeholder: 'xcov_report',
      },
      {
        name: 'includeTargets',
        label: 'Include targets (comma-separated)',
        type: 'text',
        placeholder: 'AppCore,AppUI',
      },
      {
        name: 'excludeTargets',
        label: 'Exclude targets (comma-separated)',
        type: 'text',
        placeholder: 'AppTests',
      },
      {
        name: 'jsonReport',
        label: 'JSON report',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'markdownReport',
        label: 'Markdown report',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
      {
        name: 'additionalArgs',
        label: 'Extra args',
        type: 'text',
        placeholder: '--ignore_file_path .xcovignore',
      },
      {
        name: 'cwd',
        label: 'Working dir (defaults to project root)',
        type: 'text',
        placeholder: '.',
      },
    ],
  },
  aiPrompt: {
    type: 'aiPrompt',
    label: 'AI Prompt',
    description: 'Run a non-interactive prompt through claude / codex / aider / gemini / custom CLI.',
    color: '#ec4899',
    icon: 'Sparkles',
    fields: [
      {
        name: 'tool',
        label: 'Tool',
        type: 'select',
        required: true,
        options: ['claude', 'codex', 'aider', 'gemini', 'custom'] as const,
        defaultValue: 'claude',
      },
      {
        name: 'command',
        label: 'Custom command (only when tool=custom)',
        type: 'text',
        placeholder: 'mycli --flag',
      },
      {
        name: 'prompt',
        label: 'Prompt',
        type: 'textarea',
        required: true,
        placeholder: 'Fix the failing test in src/utils.ts so that pnpm test passes.',
      },
      {
        name: 'cwd',
        label: 'Working dir (relative)',
        type: 'text',
        placeholder: '. (defaults to project root)',
      },
      {
        name: 'allowFailure',
        label: 'Allow failure (continue on non-zero exit)',
        type: 'select',
        options: ['false', 'true'] as const,
        defaultValue: 'false',
      },
    ],
  },
};

export const STEP_TYPES: readonly StepType[] = Object.keys(STEP_DEFINITIONS) as StepType[];

export function getStepDefinition(type: StepType): StepDefinition {
  return STEP_DEFINITIONS[type];
}
