// Zod schemas describing the on-disk shape of ~/.buildpilot/config.json.
// Used at startup by loadConfig() to surface clear, actionable error
// messages instead of letting a malformed config crash with a low-quality
// JSON.parse / property-access stack trace. Top-level objects are
// .passthrough() so future fields and user comments don't break older
// installs that read newer configs (forward-compat) or vice versa.

import { z } from 'zod';

// ── Sub-schemas ────────────────────────────────────────────────────────────

// Each notification / auth block is independently optional in ServerConfig.
// When a block IS present we validate every field strictly so a misspelled
// key (e.g. "botTokken") surfaces as a clean error instead of silently
// falling through to "missing required field".

export const TelegramConfigSchema = z
  .object({
    enabled: z.boolean(),
    botToken: z.string(),
    defaultChatId: z.string(),
  })
  .passthrough()
  .superRefine((val, ctx) => {
    // Cleartext + telegram-on without a token would dispatch zero-byte
    // requests to telegram.org. Surface it at parse time so users see
    // the problem before the bot fails silently at runtime.
    if (val.enabled && val.botToken.trim().length === 0) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          'telegram.enabled is true but telegram.botToken is empty — paste the token from @BotFather',
        path: ['botToken'],
      });
    }
  });

export const SlackConfigSchema = z
  .object({
    enabled: z.boolean(),
    signingSecret: z.string(),
    botToken: z.string(),
    defaultChannel: z.string(),
  })
  .passthrough()
  .superRefine((val, ctx) => {
    if (val.enabled && val.signingSecret.trim().length === 0) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          'slack.enabled is true but slack.signingSecret is empty — required for X-Slack-Signature verification',
        path: ['signingSecret'],
      });
    }
  });

export const DiscordConfigSchema = z
  .object({
    enabled: z.boolean(),
    publicKey: z.string(),
    applicationId: z.string(),
    defaultChannelId: z.string(),
  })
  .passthrough()
  .superRefine((val, ctx) => {
    if (val.enabled && val.publicKey.trim().length === 0) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          'discord.enabled is true but discord.publicKey is empty — required for Ed25519 signature verification',
        path: ['publicKey'],
      });
    }
  });

export const AuthConfigSchema = z
  .object({
    enabled: z.boolean(),
    // Session secret is auto-generated by loadConfig() when auth.enabled
    // flips to true and this field is empty, so it's tolerated here.
    sessionSecret: z.string(),
  })
  .passthrough();

export const GithubOAuthConfigSchema = z
  .object({
    clientId: z.string(),
    clientSecret: z.string(),
    redirectAfter: z.string().optional(),
  })
  .passthrough();

// Per-tool AI overrides (path + model). Both fields optional — an empty
// block means "use the hardcoded defaults from aiPrompt.ts". Nothing here
// is a secret, so no encryption/redaction layer is involved.
export const AiToolConfigSchema = z
  .object({
    path: z.string().optional(),
    model: z.string().optional(),
  })
  .passthrough();

export const AiIntegrationsConfigSchema = z
  .object({
    claude: AiToolConfigSchema.optional(),
    codex: AiToolConfigSchema.optional(),
    aider: AiToolConfigSchema.optional(),
    gemini: AiToolConfigSchema.optional(),
  })
  .passthrough();

// ── Top-level schema ───────────────────────────────────────────────────────

export const ServerConfigSchema = z
  .object({
    host: z.string().min(1, 'host must be a non-empty string (e.g. "127.0.0.1")'),
    // Port must be a positive integer in the legal TCP range. Strings are
    // rejected so users see "expected number, received string" rather than
    // EACCES at bind time.
    port: z
      .number({ invalid_type_error: 'port must be a number (1-65535)' })
      .int('port must be an integer')
      .min(1, 'port must be >= 1')
      .max(65535, 'port must be <= 65535'),
    pollIntervalSec: z
      .number({ invalid_type_error: 'pollIntervalSec must be a number (seconds)' })
      .int('pollIntervalSec must be an integer')
      .min(1, 'pollIntervalSec must be >= 1'),
    dbPath: z.string().min(1, 'dbPath must be a non-empty filesystem path'),
    // null is the documented sentinel for "no web origin" (server-only
    // mode); strings are validated as non-empty so an accidental "" is
    // rejected loudly.
    webOrigin: z.union([z.string().min(1), z.null()]),
    telegram: TelegramConfigSchema.optional(),
    slack: SlackConfigSchema.optional(),
    discord: DiscordConfigSchema.optional(),
    buildRetentionDays: z
      .number({ invalid_type_error: 'buildRetentionDays must be a number' })
      .int('buildRetentionDays must be an integer')
      .min(0, 'buildRetentionDays must be >= 0 (0 disables retention)')
      .optional(),
    auth: AuthConfigSchema.optional(),
    githubOAuth: GithubOAuthConfigSchema.optional(),
    aiIntegrations: AiIntegrationsConfigSchema.optional(),
  })
  // .passthrough() so future fields added by a newer server build don't
  // brick an older install that happens to read the same file (and
  // vice-versa). Unknown keys are simply ignored.
  .passthrough();

export type ServerConfigParsed = z.infer<typeof ServerConfigSchema>;

// ── Error formatting ───────────────────────────────────────────────────────

// Pretty-printed multi-line message describing every validation error
// at once, grouped by path. We deliberately re-format zod's default
// output because the raw issue.message strings are terse and don't
// include the offending value — confusing for users editing config.json
// by hand.
export function formatValidationError(
  err: z.ZodError,
  raw: unknown,
): string {
  const lines: string[] = [
    'Invalid configuration in ~/.buildpilot/config.json:',
    '',
  ];
  for (const issue of err.issues) {
    const path = issue.path.length > 0 ? issue.path.join('.') : '(root)';
    const received = previewReceived(raw, issue.path);
    let detail = `  • ${path}: ${issue.message}`;
    if (received !== undefined) {
      detail += `\n      received: ${received}`;
    }
    lines.push(detail);
  }
  lines.push('');
  lines.push(
    'Fix the keys above and restart the server. Unknown top-level keys',
  );
  lines.push('are ignored, so this list contains only real schema mismatches.');
  return lines.join('\n');
}

// Best-effort lookup of the offending value at `path` inside the raw
// parsed JSON so the error message can show what the user actually
// wrote. Returns undefined when the path doesn't resolve (e.g. when
// the issue is a missing-required-key check).
function previewReceived(raw: unknown, path: ReadonlyArray<string | number>): string | undefined {
  let cur: unknown = raw;
  for (const seg of path) {
    if (cur === null || typeof cur !== 'object') return undefined;
    cur = (cur as Record<string | number, unknown>)[seg];
    if (cur === undefined) return undefined;
  }
  if (cur === undefined) return undefined;
  try {
    const json = JSON.stringify(cur);
    if (json === undefined) return String(cur);
    return json.length > 120 ? `${json.slice(0, 117)}…` : json;
  } catch {
    return String(cur);
  }
}
